### ISSUE TITLE
Only download metadata needed for selected starter pack

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#531]
We should only download the [partial channel metadata](https://phabricator.endlessm.com/T34789) needed for the starter experience in the onboarding, to make the initial on-boarding flow faster, and to make it possible to include Khan Academy content in starter packs.

Subtasks:

- [x] https://github.com/endlessm/endless-key-content-private/issues/27

**Comment by manuq** [comment]
Let's try to be more specific with issue titles and descriptions :)

**Comment by manuq** [comment]
Let's assume that partial metadata will be part of the collection JSON files anytime soon. We should sync on the JSON format with the content editor devs.

For obtaining some sample partial metadata we can use a Kolibri API endpoint: https://phabricator.endlessm.com/T34789#976850

Then is a matter of importing the metadata from the JSON instead from the network (Kolibri Studio). For that we'll probably need a custom task similar to the `remoteresourceimport` task. Details in https://phabricator.endlessm.com/T34789

**Comment by manuq** [comment]
@wjt @dbnicholson that's a smart decision. Moving out of sprint.

**Comment by manuq** [comment]
This has been superceeded by "download all the metadata". Closing.
