### ISSUE TITLE
Add download button to unavailable channel

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#532]
The template of the channels custom presentation should be changed to look like this when the channel is not available:

![Image](https://user-images.githubusercontent.com/83944/238734472-5e72e436-8623-4075-9725-d29be1c1bac6.png)

That is, show a download button in the header.

Current Explore plugin can't display unavailable channels, but this draft PR can: https://github.com/endlessm/kolibri-explore-plugin/pull/530/files

So this can be done now based on the PR above assuming that unavailable channels will be navigated in the future.

What is an unavailable channel? For Kolibri, it is an imported channel without imported content. So for implementing this we can call `importchannel` (without importcontent) from the command line:

```
kolibri manage importchannel network SOME_CHANNEL_ID
```

The download implementation itself will be part of another issue. For now the button should do nothing, or should redirect to the Device tab.

**Comment by manuq** [comment]
Hint: the channel information is in the custom presentation store already. it is fetched through API `window.kolibri.getChannelMetadata()` and commited by the `setChannelInformation` mutation.

**Comment by jofilizola** [comment]
For clarification, the only difference the header of channels with unavailable content should have is a button. 
The re-style of the headers (title and description below the banner, for example) are for all. 
So, we have two tasks:
- Add a button to request the download of a full channel when it's unavailable
- New header layout for better legibility

**Comment by jofilizola** [comment]
Here are flows for browsing online-only content within channels:
https://github.com/endlessm/endless-key-content-private/issues/21#issuecomment-1564850054

**Comment by manuq** [comment]
> This task is now limited to adding a download button to the current channel header,
ok! I'm changing the issue title to account for it.

**Comment by erikos** [comment]
Landed in Ladybird 6.8-338

**Comment by erikos** [comment]
Download channel button only available in the channels that do not have content yet on the device - the button should be there in all the channels also serving as a way to download the rest of the content.

**Comment by manuq** [comment]
@jofilizola @erikos besides the partially download channel, we need to actually start a download. For that the implemented stuff in https://github.com/endlessm/kolibri-explore-plugin/pull/608 will be useful. But also we need design decisions. Should the button display a spinner while downloading? Or maybe a progress bar? Should the button display a check mark after downloading? Should it allow retrying? Basically do we want the different UI states like the resource card has.

**Comment by jofilizola** [comment]
@manuq design specs: https://github.com/endlessm/endless-key-content-private/issues/22#issuecomment-1584803343

**Comment by erikos** [comment]
The download button currently opens the Kolibri device page. That is why the button has been disabled #622 

The other piece is to differentiate between a full channel download where no item is on the device yet and when parts are there and the rest should be downloaded. Which would not be a blocker to leave that out for a first implementation. Only have the channel download for a full-offline one.

**Comment by jofilizola** [comment]
Should we close this as "won't fix" @erikos ?
