### ISSUE TITLE
Investigate full channel download from within Explore plugin

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#533]
In Kolibri if a user starts a channel download in the Device tab, the Task manager is displayed:

![Image](https://user-images.githubusercontent.com/83944/238717125-37bb8d6a-7b51-4cdd-a103-3f73046a96a0.png)

The download continues in the background when the user navigates elsewhere. And the progress can be fetched from other pages. Here the progress is shown in the Device channels page:

![Image](https://user-images.githubusercontent.com/83944/238717088-84decb9a-5998-4672-8620-13edab1f5b19.png)

So there must be a way to start a channel download in the background from within the Explore tab, by adding a task to the task manager.

Goal:
- Investigate what does the Device tab do for adding a task to the Task manager.
- Check how the same mechanism can be used to start a channel download in the background from within the Explore tab.

The button added by #532 can be used as trigger.

Note: our starter pack download is not using the tasks manager (navigating to `/device/#/content/manage_tasks` in the middle of a pack download shows nothing). This should be fixed in the future!

**Comment by manuq** [comment]
This Kolibri documentation may be relevant: https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/tasks.html

**Comment by dbnicholson** [comment]
> Note: our starter pack download is not using the tasks manager (navigating to `/device/#/content/manage_tasks` in the middle of a pack download shows nothing). This should be fixed in the future!

Are you sure about that? [CollectionDownloadManager](https://github.com/endlessm/kolibri-explore-plugin/blob/6ca399994e45dac995cf1de3c17c9a9ddd355b7a/kolibri_explore_plugin/collectionviews.py#L237) is all about tasks and enqueues the `remotecontentimport` when importing content. This is the same thing that happens from the device plugin.

**Comment by dbnicholson** [comment]
I'm pretty confident you make a `POST` request to `/api/tasks/tasks/` with a JSON body containing `type: "kolibri.core.content.tasks.remotecontentimport"` and then all the typical import parameters like `channel_id`, `node_ids`, `exclude_node_ids`, etc.

**Comment by wjt** [comment]
> So there must be a way to start a channel download in the background from within the Explore tab, by adding a task to the task manager.

@manuq Are you talking here about downloading the metadata for a particular additional channel; or downloading a particular piece of content on-demand?

**Comment by dbnicholson** [comment]
Like https://github.com/endlessm/eos-image-builder/blob/master/hooks/content/50-kolibri-content#L66 except that's written against 0.15 and the task API changed a bit for 0.16. https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/tasks.html#enqueuing-tasks-via-the-post-api-tasks-tasks-api-endpoint shows how to do it for 0.16. If you open a developer console with vanilla Kolibri you'll see requests like that from the device page.

**Comment by manuq** [comment]
@wjt yes the idea is to download a full channel in the background. This will be triggered by a button in a channel that's not available (or maybe with partial availability?).

In parallel I'm also checking how to download a single resource in the background. This will be triggered by a cloud button in resource cards that aren't available.

@dbnicholson thanks a lot for the references! Those APIs were exactly where I was heading.

**Comment by dbnicholson** [comment]
> In parallel I'm also checking how to download a single resource in the background. This will be triggered by a cloud button in resource cards that aren't available.

There's only the `remotecontentimport` task API which works at the `ContentNode` level, but I think it's likely good enough. You just specify a single element `node_ids` list then you'll only get the files associated with that node and any ascendant and descendant topic thumbnails.

**Comment by manuq** [comment]
@dbnicholson for a single resource I see a `remoteresourceimport`. The only parameter is the resource `node_id`. But seems to be in the works (it will only work with Studio 0.16). So yes, the `remotecontentimport` task should be enough for both a single resource and the full channel.

**Comment by manuq** [comment]
The `POST /api/tasks/tasks/` with the following payload parameters works for downloading a single resource:

```
{
  "type": "kolibri.core.content.tasks.remotecontentimport",
  "channel_id": "057f871caa405ec29d62ba0523c193d7",
  "channel_name": "foo",
  "node_ids": [
    "4cfbedfe9ab659d28c36069e853b6eca"
  ],
  "update": true
}
```

And the full channel can be downloaded by passing the root node in `node_ids`. That is, use the same ID as in `channel_id`.

This makes the task appear in the tasks at Device tab Task manager `/device/#/content/manage_tasks`

![Captura de pantalla de 2023-06-06 09-46-00](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/8c62d5f3-a409-462c-b02d-69a8b02376da)

Then `GET /api/tasks/tasks/{id}/` can be used with the task ID in the response to keep track of the task progress.

Since I have Kolibri setup for development, I used the API explorer by opening `/api_explorer`:

![Captura de pantalla de 2023-06-06 09-48-01](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/14eb3a94-0037-400d-b18a-226806c9109e)


For UI reasons `channel_name` is mandatory so I just passed "foo". Just like we do [when downloading the collections](https://github.com/endlessm/kolibri-explore-plugin/blob/1e8cf9e322ca480a5ce445b5ac930c1b4390c009/kolibri_explore_plugin/collectionviews.py#L125).

Ideally we would just trigger the download from the kolibri-explore-plugin and then redirect users to the Device tab.
But the requirements are that we track progress and update the state / refresh the UI. So I fear that we'll be duplicating some code with the Device plugin.

Closing as done. I will open follow-ups to actually implement the download.

**Comment by erikos** [comment]
> Ideally we would just trigger the download from the kolibri-explore-plugin and then redirect users to the Device tab. But the requirements are that we track progress and update the state / refresh the UI. So I fear that we'll be duplicating some code with the Device plugin.

Yes, is an interesting work around to re-direct to the device tab but it would break being a seamless content management experience. Some code duplication is an acceptable trade-off here I think.

**Comment by manuq** [comment]
> > Ideally we would just trigger the download from the kolibri-explore-plugin and then redirect users to the Device tab. But the requirements are that we track progress and update the state / refresh the UI. So I fear that we'll be duplicating some code with the Device plugin.
> 
> Yes, is an interesting work around to re-direct to the device tab but it would break being a seamless content management experience. Some code duplication is an acceptable trade-off here I think.

Yes, that's the requirement we have and I understand it. For the record, I wanted to state that this is not ideal.
