### ISSUE TITLE
Style card of unavailable content

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#534]
The play button ("read", "watch") should be disabled when the content is not available. And a cloud icon should be present:

![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/aa3d6d66-0845-4330-a463-e03db871bd5b)

Current Explore plugin can't display unavailable content, but this draft PR can: https://github.com/endlessm/kolibri-explore-plugin/pull/530/files

So this can be done now based on the PR above assuming that unavailable content will be navigated in the future.

Hint: content cards have the content node as parameter already. The play button ("read", "watch") should be disabled when `node.available` is false.

**Comment by manuq** [comment]
@GeorgesStavracas, I reviewed: https://github.com/endlessm/kolibri-explore-plugin/pull/547#pullrequestreview-1451962270

**Comment by manuq** [comment]
Released internally:
- Endless Key Android: Ladybird 6.2-329
- Endless Key Windows: v1.0.52
- kolibri-explore-plugin: v6.2.0

To verify this a feature flag must be enabled. For Android see https://phabricator.endlessm.com/w/apps/endlesskey/chromebook/#edit-the-kolibri-options

**Comment by manuq** [comment]
@GeorgesStavracas reopening because I've found some errors in the EkCardBody rearrangemnt (commit 6482dd174f0edf5be37d1c8108714c9b1044405b): There is a typo in BootstrapVue components: they should be `<b-container>`, `<b-row>`, `<b-col>`. Vue is raising warnings for unknown components `<v-container>`, `<v-row>`, `<v-col>`. (Note "v" instead of "b"). This suggests that the components aren't actually needed, they are probably treated as a <div>?. Sorry that I didn't saw this during review.

![Captura de pantalla de 2023-06-05 20-09-20](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/d46362c1-d582-419b-82cc-2357553de569)

**Comment by manuq** [comment]
Here is a PR that would fix the cards.

**Comment by erikos** [comment]
https://github.com/endlessm/kolibri-explore-plugin/pull/566 the PR.

**Comment by erikos** [comment]
Landed in Ladybird 6.8-338

**Comment by erikos** [comment]
The new card style can not be seen in the latest release Ladybird 6.8-338 when pulling in cloud content with NAVIGATE_UNAVAILABLE turned on.

**Comment by manuq** [comment]
Is not very useful to reopen tickets for things that have already been verified.

**Comment by erikos** [comment]
We are missing from the description: The play button ("read", "watch") should be disabled when the content is not available. **And a cloud icon should be present:**

**Comment by manuq** [comment]
> We are missing from the description: The play button ("read", "watch") should be disabled when the content is not available. **And a cloud icon should be present:**

Sorry for the confusion. We decided to split the cloud icon from this, for the sake of moving things forward. It is already implemented in #568.

**Comment by GeorgesStavracas** [comment]
So, what should we do with this ticket? As manuq mentioned, the cloud icon  and the associated download functionality is being tracked in #568, which means there are effectively two tickets tracking the same feature now.

**Comment by GeorgesStavracas** [comment]
#568 has landed

**Comment by erikos** [comment]
Deployed in Ladybird 6.10-341

**Comment by erikos** [comment]
Verified in Ladybird 6.12-342

**Comment by manuq** [comment]
> Verified in Ladybird 6.12-342

Then closing!
