### ISSUE TITLE
Add option to navigate unavailable channels and content

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#545]
Add a new plugin boolean option `NAVIGATE_UNAVAILABLE` that defaults to false. If true:
- The unavailable channels should be displayed in the Search/Library tab. That is, channels with imported metadata but without any imported content.
- The unavailable content should be displayed. Channels with partial content imported (the case of all channels in a starter pack) will also show the content not imported. The search will also show unavailable content in results.

**Comment by manuq** [comment]
This is ready for review. It's under a feature flag so it should be safe to merge.

**Comment by jprvita** [comment]
I tested this using a KOLIBRI_HOME where I previously imported the artist starter pack (to test the featured channels). Initially only the channels I had before were appearing in the Library tab, but after I stopped Kolibri, ran `kolibri manage importchannel network 2f95235c3709511fa12d007f31ed6a7b` and ran it again as specified above, I could see an extra STEM channel in the library, with what looked like a lot of content nodes. All the nodes had the same stock thumbnail, which I believe is expected. `listchannels` shows it under `pos` "None" for some reason, which I believe is fine too.
```
$ kolibri manage listchannels | grep 2f95235c3709511fa12d007f31ed6a7b
None      2f95235c3709511fa12d007f31ed6a7b        STEAM
```

Trying to access the resource from a node currently displays an error, which I also believe is expected at this point:
![Screenshot from 2023-05-25 16-38-05](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/642c0ee3-2abc-4907-b3f4-616c17e0c470)

Then I deleted and recreated my KOLIBRI_HOME, importing the artist starter pack again, and was expecting to see more channels in the library, per @manuq's comment "Current starter packs would work too as they are now importing way more metadata than needed", but it showed me the same channels as before, so IDK how to test that part. Perhaps the artist starter pack does not have more metadata then needed?

Even with the comments above, I'm considering this a CR+ and will go ahead with merging it.

**Comment by manuq** [comment]
Released internally:
- Endless Key Android: Ladybird 6.2-329
- Endless Key Windows: v1.0.52
- kolibri-explore-plugin: v6.2.0

Here is how to test this with the feature flag on Android: https://phabricator.endlessm.com/w/apps/endlesskey/chromebook/#edit-the-kolibri-options

**Comment by erikos** [comment]
Tested this yesterday in the Playthrough as working.
