### ISSUE TITLE
Channel override: Ukrainian Content

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#553]
Channel ID: 08897e003ea9489eb3d86fc94ba08c21

Styling:
- [x] Custom primary color? `#096AAD` 
- [x] Custom secondary color? `#096AAD`
- [x] Custom thumbnail? [JPEG file](https://www.dropbox.com/s/fpy8i823rfnxzmh/Thumb_Ukraine%20600x376.png?dl=0)
- [x] Custom icon? [PNG file](https://www.dropbox.com/s/wuymgav7815beym/Logo_Uktaine%20208x208.png?dl=0)
- [x] Custom header asset? [JPEG file](https://www.dropbox.com/s/mrtydl27mdx9q2f/BG_Ukraine%202560x900.jpg?dl=0)

Options:
- [x] Has dark header? YES.
- [x] Has carousel section? NO
- [x] Has filters section? NO

**Comment by jofilizola** [comment]
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/e58c437f-21e7-463a-a2a2-e3587410e273)

**Comment by erikos** [comment]
Thanks Joana for using the new template. An example of where in code this is done is https://github.com/endlessm/kolibri-explore-plugin/pull/510 with the corresponding task https://phabricator.endlessm.com/T34204

**Comment by GeorgesStavracas** [comment]
Pushed this override to https://github.com/endlessm/kolibri-explore-plugin/pull/556 but it's still building locally.

**Comment by manuq** [comment]
Released internally:
- Endless Key Android: Ladybird 6.2-329
- Endless Key Windows: v1.0.52
- kolibri-explore-plugin: v6.2.0

**Comment by erikos** [comment]
![Screenshot 2023-06-01 16 40 18](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/88354c5d-dee0-4d33-96b1-8642194814d0)
