### ISSUE TITLE
Channel override: HarperCollins

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#555]
Channel ID: (608fd926be60462aba2feccba6c050c9)

Styling:
- [ ] Custom thumbnail? JPEG
- [ ] Custom icon? PNG
- [ ] Custom header asset? JPEG file. 
Assets link: https://www.dropbox.com/sh/fhxxl2lkghw6gje/AADDfYj3LhHZsUucx79Mu5MCa?dl=0

Options:
- [ ] Should force flat display? YES
- [ ] Has search section? NO
- [ ] Has carousel section? NO
- [ ] Has filters section? NO

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/11190e25-490d-41f2-9513-735f2a12d82e)

**Comment by hydrolet** [comment]
Logo from HarperCollins attached
![image (2) (1)](https://github.com/endlessm/kolibri-explore-plugin/assets/108750056/82cbf211-4048-42f9-86aa-ea3cd43acf46)

**Comment by jofilizola** [comment]
Let's use the logo I exported, the one they've sent is super low res and, comparing to the website, looks a bit distorted... We can show them the link once it's ready and they can approve.

**Comment by jprvita** [comment]
I'm assuming this has no custom colors, since it is not in the request (only mentioning because this is the first without custom colors I come across).

**Comment by jofilizola** [comment]
Argh, i need to check the Figma's export settings. It's supposed to be much smaller. Here you have the re-exported image (replaced onn the link as well). 

About the colors: correct, no change. (I remove all of the items from the list that need no change)

![BG_HaperColllins-2560x900](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/df2e0e76-60ea-463c-af79-0d52034221eb)

**Comment by erikos** [comment]
Verified, looks good.
