### ISSUE TITLE
Fix Play button for HP5 content

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#560]
Seen in playthrough yesterday. The H5P content doesn't match any media type so the label is empty. They should look like HTML ones. Label: "interact".

![Image](https://user-images.githubusercontent.com/83944/242909692-8cea6550-c6a3-4e25-9c3d-135baebb11a5.png)

**Comment by erikos** [comment]
We can move this out to after the update 1 Ladybug release.

**Comment by erikos** [comment]
QA ready in Ladybird v6.30.0

**Comment by erikos** [comment]
The play button is working - although the button for the interact is not displaying with the gray (grey) circle. 

![Screenshot from 2023-07-24 14-47-27](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/21bc8174-2836-4bac-8d13-f377f2b23862)
![Screenshot from 2023-07-24 14-46-44](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/2c4cd5b5-0393-4261-b085-3aa8a10193fd)
