### ISSUE TITLE
Add channel information to cards in Discovery

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#561]
Content cards in Discovery should show the channel icon and title. Just like the content cards in the Library do.

![Image](https://user-images.githubusercontent.com/83944/242910436-3f83df54-bc35-4641-9037-08db9d1d84a4.png)

**Comment by erikos** [comment]
I would say earliest in the second week of the J-sprint when we do polish and bug fix and landed all the content management functionality.

**Comment by manuq** [comment]
> I would say earliest in the second week of the J-sprint when we do polish and bug fix and landed all the content management functionality.

I had this almost ready so I decided to finish it while I'm at it :)

**Comment by erikos** [comment]
Should definitely be in Ladybird 6.8-338

**Comment by erikos** [comment]
Verified in Ladybird 6.8-338 in the Discovery page in the _Your channels_ section.
