### ISSUE TITLE
Implement download of single resource

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#568]
Add a "cloud" button to resource cards that are unavailable. When clicked, the download should start in the background (see #533). The task ID must be stored somewhere in order to keep track of progress and query until the task finished. When the download is complete the card should refresh to be available for playing.

Design reference: https://github.com/endlessm/endless-key-content-private/issues/17#issuecomment-1551338721

Challenge: how would this work in custom presentations? Since they are separate webapps it could be problematic.

**Update:** A number of subtasks have popped up:
- [x] #600 
- [x] #601 
- [x] #602 
- [x] #603

**Comment by jofilizola** [comment]
Card states, when online
![image](https://github.com/endlessm/endless-key-content-private/assets/51095367/bed2c056-e2a5-47a8-a1e6-19042a66f861)

when offline
![image](https://github.com/endlessm/endless-key-content-private/assets/51095367/061f0642-faa7-44e0-8616-6e2becd5df7f)

**Comment by jofilizola** [comment]
Link to design : 
https://www.figma.com/file/ItL7d0N9yJALcu12S50dQn/EK-Ladybird?type=design&node-id=468%3A176283&t=0QSUjCPRYQaJWGM2-1

**Comment by erikos** [comment]
`Challenge: how would this work in custom presentations? Since they are separate webapps it could be problematic.
`
@manuq this sounds concerning. Have you found a way to make this work for our custom presentations?

**Comment by manuq** [comment]
Update: The UI is in place:
https://github.com/endlessm/kolibri-explore-plugin/assets/83944/59d32b58-e25c-4201-add7-5a79c986b978

I had to do lateral things:
- Resurrect the test page that had regressed. This is to work on the theme and UI without actual logic (video above).
- Workaround i18n in custom presentations.

Currently I'm working on a global download manager. Since resource cards are in multiple views there has to be a single place to manage the downloads. It will handle full channels also. The download of collections was simpler because all happens in its own view (DownloadPage).

> `Challenge: how would this work in custom presentations? Since they are separate webapps it could be problematic. ` @manuq this sounds concerning. Have you found a way to make this work for our custom presentations?

The idea is to add one API to communicate the custom presentation with the global download manager mentioned above. Unlike the Explore plugin, custom presentations are separate webapps and can't call Kolibri directly, only through the [kolibriAPI](https://github.com/endlessm/kolibri-explore-plugin/blob/master/kolibri_explore_plugin/assets/src/kolibriApi.js) that is exposed as `window.kolibri`.

**Comment by manuq** [comment]
Moving to current sprint.

**Comment by manuq** [comment]
OK, after the lateral PRs landed here is a PR that downloads the resources: #608

It should work in all views (search, custom presentations home page, topic page, etc). The missing piece is refreshing the node in the views after completion when the "node updated" signal is emited. But the content can be opened.


https://github.com/endlessm/kolibri-explore-plugin/assets/83944/fbff2e42-67a3-40b5-8323-36d477e4979d

**Comment by erikos** [comment]
Deployed in Ladybird 6.10-341

**Comment by erikos** [comment]
Verified in Ladybird 6.10-341: the item can be downloaded and used. The major follow up is that the card does not update yet.

**Comment by jofilizola** [comment]
I just came across the "download error" state, I hit the refresh button, but icon is gone.
Pack: Explorer
Channel (not downloaded): WiiXii
I tried to downloaded the first two resources of the first folder, the third gave me error.
On the home of the channel, the card looks unavailable, with no action icons
If I go to the topic page it shows as available (with thumb) and content has downlaoded.

**Comment by jofilizola** [comment]
Is it the same issue? 
I saw this state, and then it's not that the thumbnail didn't update, the whole card was unclickable:
<img width="277" alt="Screenshot 2023-06-16 at 14 13 40" src="https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/28012880-2bbf-42e2-8b22-0975d984a097">
