### ISSUE TITLE
Add filtering functionality for online/offline content to the search results

### ISSUE THREAD

**Issue by jprvita** [endlessm/kolibri-explore-plugin#572]
Search results, unfiltered:
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/ecb43837-e6b6-4308-a872-efae6e286eb3)

Search results, filtered:
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/e300b397-f1ea-489a-9dc9-2c33307b6168)

_Originally posted by @jofilizola in https://github.com/endlessm/kolibri-explore-plugin/issues/569#issuecomment-1579260526_

- [ ] #570

**Comment by jprvita** [comment]
@manuq provided some insight on https://github.com/endlessm/kolibri-explore-plugin/issues/569#issuecomment-1579510036

> The control itself could be a BootstrapVue switch style checkbox: https://bootstrap-vue.org/docs/components/form-checkbox#individual-checkbox-switch-style
> 
> The spec from @jofilizola shows a checkbox control from Material, but I'm afraid we are using Bootstrap through BootstrapVue. The only exception is that we use icons from Material. Switching entirely to Material would be a bigger change, and mixing UI frameworks is not convenient.

**Comment by jofilizola** [comment]
The control can be the Bootstrap one!

**Comment by jprvita** [comment]
This is what I get with #576:
![Screenshot from 2023-06-07 17-02-51](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/b37a0900-e285-4dcb-9618-2afe8c5bb8a3)
![Screenshot from 2023-06-07 17-03-09](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/b3788c6b-da91-4b80-a6c9-fe56364d0331)

**Comment by manuq** [comment]
Reviewed https://github.com/endlessm/kolibri-explore-plugin/pull/576#pullrequestreview-1469821904

**Comment by jprvita** [comment]
Addressed changes, ready for review again.

**Comment by jofilizola** [comment]
I noticed that when the switch is ON, it shows unavailable content.
It seems more intuitive to me to filter out unavailable content when the switch is on, so the other way round.

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/05d3dda4-8f9d-41c1-9b53-0622662e7337)

**Comment by erikos** [comment]
In the Ladybird 6.8-338 release we do not see the slider in the Library view.

**Comment by erikos** [comment]
Follow up issue is #596 for better wording and behavior of th ebutton.
