### ISSUE TITLE
Reorganize channel header

### ISSUE THREAD

**Issue by GeorgesStavracas** [endlessm/kolibri-explore-plugin#574]
This is a side task related to https://github.com/endlessm/kolibri-explore-plugin/issues/532, which was focused on the download button.

This is how the channel header should look like:

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/38d90484-e324-4667-913d-780cf6830ad8)

**Comment by jofilizola** [comment]
Not for now, needs more study.
