### ISSUE TITLE
Study creating Github release notes for kolibri-explore-plugin automatically

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-explore-plugin#577]
kolibri-explore-plugin releases when have a new tag.  It will be good if we can have the release note like https://github.com/learningequality/kolibri/releases

**Comment by starnight** [comment]
@manuq has an initial idea: range of commits between the new tag and the previous release tag `git range-diff v6.2.0...v6.1.0`

**Comment by starnight** [comment]
I notice document [Automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).  The [Configuring automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) section looks interesting!

**Comment by starnight** [comment]
The [Release step](https://github.com/endlessm/kolibri-explore-plugin/blob/1e8cf9e322ca480a5ce445b5ac930c1b4390c009/.github/workflows/main.yml#LL44C15-L44C22) using [softprops/action-gh-release](https://github.com/softprops/action-gh-release) does the release action on GitHub.  It also supports loading release notes from a path in repository's build to allow for the flexibility of using any changelog generator for releases.

But, current kolibri-explore-plugin CI does not use `body_path`.

**Comment by starnight** [comment]
Another test:
Click kolibri-explore-plugin's [Releases](https://github.com/endlessm/kolibri-explore-plugin/releases) -> the edit icon of `[v6.2.0](https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v6.2.0)` -> Click "Generate release notes" button, then it will generate a note like ![image](https://github.com/endlessm/kolibri-explore-plugin/assets/2100946/dbe786f3-d1a3-4632-b59a-b991a6f14856)

I think this is what @erikos want!?

**Comment by manuq** [comment]
That's beautiful!
