### ISSUE TITLE
Explore plugin release fails with "GitHub Releases requires a tag"

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#589]
The last "Bump version to release" action succeded to upload the WHL file to PyPi. But failed to build the apps bundle https://github.com/endlessm/kolibri-explore-plugin/actions/runs/5243316309/jobs/9467897415 with error "GitHub Releases requires a tag"

**Comment by starnight** [comment]
According to the [Usage of action/checkout@v3](https://github.com/actions/checkout/blob/v3.5.3/README.md#usage)
```
# The branch, tag or SHA to checkout. When checking out the repository that
# triggered a workflow, this defaults to the reference or SHA for that event.
# Otherwise, uses the default branch.
ref: ''
```
The **ref** is the **reference** or **SHA** when trigger the workflow, not like normal simple `git clone`.  So, the following **checkouts** are at the original reference, not the commit after bump version.

Sorry, I do not understand action/checkout enough.

**Comment by starnight** [comment]
Because `github.ref` is not at a tag, s[oftprops/action-gh-release's optional **tag_name**](https://github.com/softprops/action-gh-release#-customizing) is not at a tag, too.  And, it shows "requires a tag" error.

**Comment by manuq** [comment]
That's fantastic! Awesome work @starnight !!
