### ISSUE TITLE
Download additional channel metadata in the background

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-explore-plugin#592]
In #548 / #580, we added a system where kolibri-explore-plugin downloads metadata for channels from _all_ content collections, instead of just channels from the initial content collection. At the moment, this is an extra stage in that initial content import which blocks the UI until it is finished. Instead, we would like for this additional metadata download to happen in the background while the user is browsing content.

**Comment by wjt** [comment]
There are some related PRs for this that we should tie up. But this is still not the case - the additional collections are fetched as part of the onboarding flow. It's not too slow though – we don't include massive channels like Khan Academy! – and this way we don't have to deal with inconsistent state.

**Comment by dbnicholson** [comment]
I whipped together something in https://github.com/endlessm/kolibri-explore-plugin/tree/background-downloads. It works pretty nicely but needs a little polish and I need to figure out the right way to ensure incomplete tasks are restarted when the app restarts.

**Comment by dbnicholson** [comment]
I'm going to make a new release so this can be tested out in the apps.

**Comment by dbnicholson** [comment]
This has been released as kolibri-explore-plugin 6.39.0 with Android Manatee 6.39-393 and Windows 6.39.1.0.

@vanessa-chang could you test out the Android app from internal testing?

**Comment by vanessa-chang** [comment]
I’ve tested the new beta 6.39-393:
- the content pack download speed is back to normal 
-  the contents are revealed after all downloads complete (~app. 10mins of app running time) & it’s show.n after the page is refreshed by switching the tab or restarting the app
-  the app shows a black screen when restarting the app during metadata download (still needs a further clarification)

I will report another ticket for the back screen issue once it’s clarified.

I prefer to have it fixed before we push to the production. Let me know if you have any suggestions. Thank you

**Comment by dbnicholson** [comment]
> * the app shows a black screen when restarting the app during metadata download (still needs a further clarification)
> 
> I will report another ticket for the back screen issue once it’s clarified.

Please do. I have a feeling this is because the background downloads never actually stop when the app is closed. https://github.com/learningequality/kolibri/pull/11120 will help that a lot but hasn't been released yet.

**Comment by vanessa-chang** [comment]
@dbnicholson thanks. I have open the ticket #769 for the issue. I currently report in the Kolibri-explore-plugin repo. However, as this issue cannot be reproduced in the Windows app, let me know if I should file in the other repo for a correction. Thanks.
