### ISSUE TITLE
User Testing: switch online/offline

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#595]
https://github.com/endlessm/kolibri-explore-plugin/issues/572

On (default): show all content
Off: show only dowloaded

On: show only downloaded
Off (defaults): show all content

**Comment by manuq** [comment]
Is this a duplicate of #572 ?

**Comment by wjt** [comment]
I think this is actually a duplicate of :

- [ ] https://github.com/endlessm/kolibri-explore-plugin/issues/596

so I am closing it as such.
