### ISSUE TITLE
Library: change behavior and labeling for filtering functionality for online/offline content of search results 

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#596]
Follow up of #572

Joana thinks the toggle for showing only downloaded content should be the other way around: it should be off by default, and when enabled should reduce the visible content. The label should be: “Only show downloaded items”

**Comment by jprvita** [comment]
@jofilizola Have you decided on the final label for the button yet?

**Comment by wjt** [comment]
The label we discussed was:

> (• ) Only show downloaded items

**Comment by jprvita** [comment]
> The label we discussed was:
> 
> > (• ) Only show downloaded items

I'm just trying to understand if that decision is final, as up until late next week it was still TBD

**Comment by wjt** [comment]
Yes, that was the string that was finalised today

**Comment by wjt** [comment]
Update: the string may not be final :)

**Comment by jprvita** [comment]
Ready for review

**Comment by manuq** [comment]
merged!

**Comment by erikos** [comment]
Deployed in Ladybird 6.10-342

**Comment by erikos** [comment]
Verified in Ladybird 6.12-342
