### ISSUE TITLE
Browse content: NAVIGATE_UNAVAILABLE is not set to true by default

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#599]
Tested with Ladybird 6.8-338

We need to set the option in order to browse content that is not on your device.

**Comment by jprvita** [comment]
I believe #605 is enough to fulfill the requirements of this ticket, although there is more work related to this, coming up in #596.

**Comment by erikos** [comment]
Deployed in Ladybird 6.9-339 to internal testing.

**Comment by erikos** [comment]
Works as epected.

**Comment by manuq** [comment]
> Works as epected.

OK, marking the issue as done.
