### ISSUE TITLE
Use the new "extras" collection

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-explore-plugin#606]
When importing metadata for additional channels outside the selected starter pack (#548), we would like to include channels which are considered part of the Endless Key project but are not included in _any_ of our starter packs. With the changes in endlessm/endless-key-collections#27, these extra channels are now specified by `extras-0001.json` from endless-key-collections.

- [x] Update [our system for downloading extra channel metadata](https://github.com/endlessm/kolibri-explore-plugin/blob/master/kolibri_explore_plugin/collectionviews.py#L74-L76) to also use channels from `extras-0001.json`.
- [ ] Verify that kolibri-explore-plugin displays a _complete_ set of channels to explore after stepping through the onboarding process and downloading a starter pack.

**Comment by manuq** [comment]
Merged the extras collection. I will work on decoupling the collection update from software update in #610

**Comment by erikos** [comment]
Ladybird 6.10-341 has it.

**Comment by erikos** [comment]
The channels here are:
Channels include:

- Blockly Games (I included this for the Spanish folder)
- EiE Familias
- The SciGirls Collection (en español)
- PhET Interactive Simulations (es)
- Pilas Engine
- Sikana (Español)
- WiiXii
- електронні книги HarperCollins
- Українською
- California Academy of Sciences (en Español)
- California Academy of Sciences

We need to see how that looks like in practice. With our flat custom presentation for Blockly Games. How does the channel look like when we have English and Spanish content? Sikana (Esp) - how does the channel look like - we have only the DIY part of Sikana. Actually, should all of Sikana be part of our catalog now?
