### ISSUE TITLE
Decouple collections from app builds

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#610]
Fetch the collection JSON manifests from Github release. Currently we serve them as static files which are included in the wrapper apps (Android, Windows) at build time. This way the collections release will be decupled from software releases.

PRs:
- [ ] https://github.com/endlessm/kolibri-installer-android/pull/150
- [ ] https://github.com/endlessm/endless-key-app/pull/122
- [ ] https://github.com/endlessm/kolibri-explore-plugin/issues/610

**Comment by manuq** [comment]
I also created PRs for the wrapper apps, so they stop bundling the collections.

**Comment by erikos** [comment]
Let's move to the next iteration to not risk any issues before we get the Ladybug release out.

**Comment by manuq** [comment]
> Let's move to the next iteration to not risk any issues before we get the Ladybug release out.

Sounds good! I'm also unassigning myself so others can take it from here. The PR already got good feedback from @dylanmccall @dbnicholson and @pwithnall .

**Comment by dylanmccall** [comment]
To smooth the transition here, I am proposing two more PRs which only affect the build system:

- endlessm/kolibri-installer-android#152
- endlessm/endless-key-app#124

**Comment by dbnicholson** [comment]
Last night I whipped up a PR to publish the endless-key-collections JSON to [GitHub Pages](https://github.com/endlessm/endless-key-collections/pull/29). I think we should go back to @manuq's PRs and use https://endlessm.github.io/endless-key-collections/ as the base URL.

**Comment by manuq** [comment]
Blocking until after ISTE. Please unblock and review again after it.

**Comment by manuq** [comment]
I'm deassigning myself from this one. Someone else could follow up the PR.

**Comment by manuq** [comment]
We decided to don't go this way.
