### ISSUE TITLE
Bad pluralisation of “1 results” in search

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-explore-plugin#612]
If your search has 1 result, the title reads (e.g.)

> 1 results for “cookie” to Watch

It should read:

> 1 result for “cookie” to Watch

![Screenshot 2023-06-14 16 33 45](https://github.com/endlessm/kolibri-explore-plugin/assets/86760/4c7d6884-36ed-45ac-aa3a-aeb118966d4c)

**Comment by manuq** [comment]
Ready for review. Disclaimer: I know this is not a priority but I happened to be working on the Search page.

Here is the documentation: https://kolibri-dev.readthedocs.io/en/develop/i18n.html#icu-message-syntax

**Comment by erikos** [comment]
The PR is https://github.com/endlessm/kolibri-explore-plugin/pull/623

**Comment by manuq** [comment]
> The PR is #623

@erikos ah I see what's happening here! The board has a simplified view of the issue that doesn't show the automatically added comments:
![Captura de pantalla de 2023-06-16 16-40-17](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/031a71f7-c4ab-4c0c-805d-80084b3e0932)

**Comment by erikos** [comment]
Can be verified in Ladybird 6.15-346

**Comment by vanessa-chang** [comment]
Verified passed in Ladybird 6.15-346
