### ISSUE TITLE
Fix webpack errors

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#614]
Local development has become a bit difficult when we migrated to Kolibri 0.16 alpha14, and even more when migrated to alpha15. This is because webpack is showing a overlay with multiple errors on each page reload. So we devs have to close 6 or 7 dialogs each time code changes.

There is no webpack configuration in kolibri-explore-plugin directly. Instead the configuration is picked from kolibri-tools. See `WebpackBundleHook` in https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/plugins.html?highlight=plugin#example-implementation

We should make sure that the plugin has the same webpack version than Kolibri.

- [ ] https://github.com/endlessm/kolibri-explore-plugin/pull/615

**Comment by manuq** [comment]
Sorry, let's do this again. Now it correctly sets the same versions as Kolibri alpha15: https://github.com/endlessm/kolibri-explore-plugin/pull/619

**Comment by erikos** [comment]
I guess works, nothing visible broke.
