### ISSUE TITLE
Update card after download of single resource

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#625]
Follow up of #568

At the moment when the download of the single resource has not finished the card is not updating. No thumbnail for the item is shown. 

- [ ] https://github.com/endlessm/kolibri-explore-plugin/pull/629
- [ ] https://github.com/endlessm/kolibri-explore-plugin/pull/634

**Comment by erikos** [comment]
Potentially this is not an issue anymore when we have the thumbnails downloaded as part of the metadata. Not sure if there are any other consequences than the thumbnail not being displayed.

**Comment by manuq** [comment]
@erikos thanks for splitting this into a separate task.

> Potentially this is not an issue anymore when we have the thumbnails downloaded as part of the metadata. Not sure if there are any other consequences than the thumbnail not being displayed.

Right. If we assume that thumbnails will be there, I can workaround by just setting the card to "available" in the frontend.

**Comment by manuq** [comment]
I managed to do this reactively (without any reloading) in the Search page. Adding the PR as a subtask. Next is the custom presentation.



https://github.com/endlessm/kolibri-explore-plugin/assets/83944/33cb2182-c4f1-4eb4-b6f9-1e2423440bd7

**Comment by manuq** [comment]
I'm still not sure why the nodes keep cached in the custom presentation, but I managed to workaround it in a separate PR.

So far I did Home, I still need to do this in 3 more views:
- packages/template-ui/src/views/ListSection.vue
- packages/template-ui/src/views/Section.vue
- packages/template-ui/src/components/FilterResult.vue

**Comment by manuq** [comment]
Template partr ready, considering every case where we have downloadable cards in the custom presentation https://github.com/endlessm/kolibri-explore-plugin/pull/634

**Comment by manuq** [comment]
I'm going to merge as-is because there were reviews already and we can improve in the future. Specially finding out what's the matter with kolibri cache.

**Comment by vanessa-chang** [comment]
Verified passed in Ladybird 6.15-346.

Windows issue: #641
