### ISSUE TITLE
Icon not updated correctly when card download fails to start

### ISSUE THREAD

**Issue by jprvita** [endlessm/kolibri-explore-plugin#632]
I am getting some "permission denied" (403) errors in my test setup when trying to access the `tasks` API in Kolibri. On the UI this translates to nothing happening when clicking the button to download the content for a card. The button reacts with the clicked animation, but nothing else happens and the icon does not change.

When this happens the icon should change to the failed state to inform the user.

**Comment by jprvita** [comment]
Ready for review with #633. This is how it looks with those changes:

https://github.com/endlessm/kolibri-explore-plugin/assets/73894/bec09dc4-e625-4cf3-a7e4-0849e4d740ff

**Comment by manuq** [comment]
Excellent.

**Comment by erikos** [comment]
Can be verified in Ladybird 6.15-346

**Comment by vanessa-chang** [comment]
Verified passed in Ladybird 6.14-345 / 6.15-346 & Windows 6.15.0.0
