### ISSUE TITLE
"Something Went wrong" error is always shown after download completes

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#639]
"Something went wrong" error is always shown after download completes.

This issue was seen in v6.9-340 and the latest package v6.14.345

![Screenshot 2023-06-14 5 29 41 PM](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/4d09d42e-5926-4dff-a36e-baf4151e396a)

I'm seeing this issue today. (test package: v6.9-340)
1. After content completes the download, it shows a "Something went wrong!" message.
2. Press "try again" button does not help.
3. Close and reopen the app, it will then running into this issue.

It fails twice with the explorer pack download for me today. (failure rate: 2/2)
It maybe worth to give it a try to see if you can reproduce the issue. I will try downloading the other content pack too.

_Originally posted by @vanessa-chang in https://github.com/endlessm/kolibri-explore-plugin/issues/598#issuecomment-1590846581_

**Comment by manuq** [comment]
Ready for review. I've found 3 separate issues.

**Comment by erikos** [comment]
Available in Ladybird 6.19-352

**Comment by erikos** [comment]
From Vanessa and me: this one is fixed and has not shown up for a long time.
