### ISSUE TITLE
Missing channel icons in the feature channels

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#642]
Tested all 6 content packs in both windows and android. There are 2 channel icons missing when they're listed in the "Your channels" row.

Explorer: Ocean X in the feature channel doesn’t have the channel icon
Scientist: PhET does not have the channel icon

If you switch to the library view, the channels icons are there.

![Screenshot 2023-06-16 4 33 44 PM](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/522c587d-24be-4514-b444-26bfb2ba3f10)

**Comment by jofilizola** [comment]
@vanessa-chang I can see the icons on the Online Instance, was this fixed?

**Comment by vanessa-chang** [comment]
@jofilizola It's not yet fixed in the apps. (ie. Manatee 6.38-392)

**Comment by dbnicholson** [comment]
I was able to reproduce this with the Scientist pack and PhET. In the HTML it has:

```
<div data-v-2bf1c6d8="" data-v-4a5650a5="" class="bg-white thumbnail mr-3 rounded-logo md" style="background-image: url(&quot;null&quot;);"></div>
```

Note `style="background-image: url(&quot;null&quot;);"`. Whereas a successfully displaying thumbnail for STEAM has:

```
<div data-v-2bf1c6d8="" data-v-4a5650a5="" class="bg-white thumbnail mr-3 rounded-logo md" style="background-image: url(&quot;http://127.0.0.1:57697/static/icons/steam.png&quot;);"></div>
```

Not sure what's going on there yet.

**Comment by dbnicholson** [comment]
I could be wrong, but it seems like the missing PhET English is because #664 only specified an icon for the Spanish channel. SImilarly, OceanX (`85b42a40745f4e2392ed62e72d4dad6e`) doesn't have an entry in `ChannelCardIcons`.

@jprvita do you have time to look at these?

**Comment by dbnicholson** [comment]
Hmm. I guess what's supposed to be happening is that when there's not a custom icon it falls back to the base64 inlined thumbnail in the channel data. Why that's working on the Library page and not the Discovery page, I don't know.

I'm getting too far out of my element, but it seems that the way the `EkChannelCard`s are displayed is different between `SearchPage` (which uses `AlphabeticalChannelsList`) and `DiscoveryPageContenPacks` (which builds them inside `EkSlidableGrid`).

**Comment by dbnicholson** [comment]
I think I see it. `DiscoveryPageContenPacks` uses the `ContentNodeExtrasViewset` to query for featured channels. However, that's only returning the root node of the channel, not the channel data itself. Presumably, the PhET channel does not have a thumbnail set on the root node and what's returned is `null`.

Instead, it should use the get the channel data from `rootNodes` using the channel IDs in the returned response. Ideally there would be a backend API that simply returned the channel metadata after filtering for nodes with the specified tags.

**Comment by dbnicholson** [comment]
I'm going to make a release so this can be tested.

**Comment by vanessa-chang** [comment]
#780  is reported. Let's follow the ticket there.
