### ISSUE TITLE
Change the SciGirls background asset

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#666]
We changed the theme background color, and now the asset doesn't match. New asset attached.
![BG_SciGirls_2560x900](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/c0a111d4-36c2-4826-a7d9-4ca33dda2491)

- [ ] SciGirls in English ID: 1b1fc9bd453a4c52bb5628d9ae804ede\
- [ ] SciGirls in Spanish ID: ee52db4a62a94e9683599af8782f2d03

**Comment by manuq** [comment]
Ready for review. Note, I compressed the PNG because it was big (from 404K to 84K).

By the way, we are not showing these assets anymore in the new header design. Should we remove them all instead?

**Comment by jofilizola** [comment]
We can leave as just the background color, that's fine. I will archive this
