### ISSUE TITLE
Channel card visual improvements

### ISSUE THREAD

**Issue by GeorgesStavracas** [endlessm/kolibri-explore-plugin#671]
We've discussed in place some improvements to the channel card visuals, mainly:

 * Make the channel banner squared at the bottom
 * Make channel cards always white
 * Add shadows to unhovered cards
 * Change background of the library page

**Comment by GeorgesStavracas** [comment]
This has been verified and deployed

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon) - pass from our side
