### ISSUE TITLE
Revisit line clamp

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#676]
We have a dependency [vue-clamp](https://vue-clamp.vercel.app/) for it. Modern CSS already has it: https://caniuse.com/?search=line-clamp but `vue-clamp` doesn't fallback to this CSS at all. Instead it has a resize observer and does calculations that may be affecting performance.

Kolibri is also doing this with CSS in a TextTruncatorCss component that we should be using directly or borrowing: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/TextTruncatorCss.vue

**Comment by manuq** [comment]
One more reason to do this: the "ResizeObserver loop limit exceeded" we are constantly seeing while developing seems to come from the [resize-detector](https://www.npmjs.com/package/resize-detector) dependency of vue-clamp.

![Captura de pantalla de 2023-06-26 16-11-14](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/0955ba1c-93fc-40a1-87aa-c0260da71bdf)

**Comment by erikos** [comment]
Archiving without further QA. Would be a dev-QA.
