### ISSUE TITLE
Make spacing of Discovery page sections homogeneous

### ISSUE THREAD

**Issue by GeorgesStavracas** [endlessm/kolibri-explore-plugin#679]
The spacing between the "Your channels" and "Just for you" sections doesn't match the rest of the page's spacing. That should be fixed.

Joana also wanted the spacing between the title and the cards reduced.

**Comment by wjt** [comment]
https://github.com/endlessm/kolibri-explore-plugin/pull/677 implemented these changes and it has long since been released.
