### ISSUE TITLE
Margins around content node download buttons are inconsistent

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-explore-plugin#690]
The download buttons for content nodes appear to have no bottom margin. As a result, they sometimes appear too close to the bottom edge of each content card:

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/132063/187e716e-5cf3-402e-94a9-e513e8da65a0)

**Comment by erikos** [comment]
Bottom margins look fine. The part missing is to center the label with the button. Will open follow up ticket.
