### ISSUE TITLE
Fix alignment of pills in Channel view

### ISSUE THREAD

**Issue by GeorgesStavracas** [endlessm/kolibri-explore-plugin#694]
The filter pills in the Channel view have their inner texts vertically misaligned. This is driving Joana mad, and nobody likes when our only designer is going crazy on alignment. Let's fix that.

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/1bc99cf4-a859-49c5-95b9-d287bbc4cd3d)

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon) - pass from our side.

**Comment by vanessa-chang** [comment]
@jofilizola Joana, what do you think about the new fix?  :)

**Comment by wjt** [comment]
It also looks good to me [here](https://key.endlessos.org/en/explore/#/topics/1520f018610256549c98ca0140cceebe). I assume Joana will speak up if she disagrees :)
