### ISSUE TITLE
Release name of the Android app has changed

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#705]
![Screenshot from 2023-07-17 08-21-33](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/bb967727-9052-4830-a6fb-5555914e7650)

Instead of our release name like _Ladybird 6.26-365_ I see the date there _2023-07-13_

**Comment by dbnicholson** [comment]
I merged the kolibri-installer-android fix, so I'm going to kick a new upload build now.

**Comment by erikos** [comment]
![Screenshot from 2023-07-31 10-28-58](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/889aa396-181b-458d-a297-156dbb23d12e)
Looking good.
