### ISSUE TITLE
Channel override: Blockly Games

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#708]
Channel ID: ed519e3b798147569b46cb550dbfc373 ( token is: fabaz-lodal)

Note: Channel cards have the special small thumbnail override (I don't remember if it was automatic)

Styling:
- [ ] Custom thumbnail? https://www.dropbox.com/s/oaiisyr7dpwrji6/Thumb_Blockly%20600x376.png?dl=0
- [ ] Custom icon? https://www.dropbox.com/scl/fi/elfap8o3j1mp027ifqj6x/Logo_Blockly-208x208.png?rlkey=tu9jul63cldrypz4j3rn96gui&dl=0

Options:
- [ ] Has search section? NO
- [ ] Has carousel section? NO
- [ ] Has filters section? NO

**Comment by hydrolet** [comment]
I can't seem to edit the original post, but the token is: fabaz-lodal :)

**Comment by hydrolet** [comment]
Content packs have been updated to include references to the new forked Blockly channel. Also, both online and dev instances have been updated.

**Comment by vanessa-chang** [comment]
The new `blocky` channel is landed in the latest internal testing branch.

The customized presentation is missing as in:
- Featured channel (Inventor)
![image](https://github.com/endlessm/endless-key-content-private/assets/31236978/8ddb0ef8-82e8-45e1-b889-20c220fd6b87)
- Channel list in the Library view
![image](https://github.com/endlessm/endless-key-content-private/assets/31236978/4886d823-9544-419c-a6cf-343879fc7526)

**Comment by hydrolet** [comment]
Channel ID is ed519e3b798147569b46cb550dbfc373

**Comment by erikos** [comment]
https://github.com/endlessm/kolibri-explore-plugin/blob/master/packages/template-ui/channel-overrides/blockly-games/options.json has currently the following settings:

{
  "hasFlatGrid": true,
  "hasCarousel": false,
  "hasFilters": false,
  "mediaQuality": "low"
}

So we should remove the  "hasFlatGrid": true. And add "hasSectionsSearch": false

**Comment by jprvita** [comment]
Created a PR using the patch @erikos sent me on slack.

**Comment by erikos** [comment]
Merged PR.

**Comment by erikos** [comment]
Landed in 6.33-383


![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/99d8a1ea-a45b-454a-a278-f9809dbb3e2d)
![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/4857df01-6432-47ff-875a-1269c133349d)
