### ISSUE TITLE
Channel override: Virtual Science Teachers

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#731]
Channel ID: eb4373b5da054c07879d0c969dc1976a

Styling:
- [ ] Custom primary color? #3566E0
- [ ] Custom secondary color? #3566E0
- [ ] Custom thumbnail? [Provide JPEG file for the channel card](https://www.dropbox.com/scl/fo/qqbis1ph7r7idss6tgvs4/h?rlkey=82oi5usr7l8dq4cqg1327gozi&dl=0)
- [ ] Custom icon? [Provide PNG that will replace the channel icon uploaded at Kolibri Studio](https://www.dropbox.com/scl/fo/qqbis1ph7r7idss6tgvs4/h?rlkey=82oi5usr7l8dq4cqg1327gozi&dl=0)

Options:
- [ ] Should force flat display? YES
- [ ] Has search section? NO
- [ ] Has carousel section? NO
- [ ] Has filters section? NO
- [ ] Display logo in header? YES

Preview:
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/062958b0-5554-4af6-a0b2-bbc45efc1342)

**Comment by erikos** [comment]
Available in https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v6.35.0 and in internal testing in the Android app.

**Comment by erikos** [comment]
Presentation looks good.
