### ISSUE TITLE
Change the initial screen so it doesn't offer the USB option.

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-explore-plugin#732]
Following https://github.com/endlessm/kolibri-explore-plugin/issues/723
Drop the Endless Key USB option from welcome screen.
![Onboarding_Get_Started](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/460b0c76-63e2-4cc7-99fc-a518751a83e2)
![Onboarding_Get_Started_new](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/32823102-1ff3-4a24-bdf3-e7cca64986dc)

**Comment by erikos** [comment]
I guess removing the related views like https://github.com/endlessm/kolibri-explore-plugin/blob/master/packages/welcome-screen/src/views/UsbDriveConnection.vue or assets like https://github.com/endlessm/kolibri-explore-plugin/blob/master/packages/welcome-screen/src/assets/usb-connect.jpg will be part of https://github.com/endlessm/kolibri-explore-plugin/issues/733 and this is only about removing the option from the welcome screen, right?

**Comment by wjt** [comment]
I think so – but I'm not too familiar with this codebase.

**Comment by erikos** [comment]
Available in **Ladybird-632.380**


![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/cbb83810-deab-489f-b4a1-f5eedf78074f)

**Comment by vanessa-chang** [comment]
Verified Passed in Chromebook: Ladybird 6.32-380 and Windows: 6.32.1.0
