### ISSUE TITLE
Drop all the welcome-screen USB APIs

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-explore-plugin#733]

**Comment by jofilizola** [comment]
@starnight @dbnicholson Is this a duplicate?
https://github.com/endlessm/kolibri-installer-android/issues/171
https://github.com/endlessm/endless-key-app/issues/145

**Comment by starnight** [comment]
Yes!  I think this has been covered by both [Stop using the welcome-screen USB APIs on Windows](https://github.com/endlessm/endless-key-app/issues/145) and [Stop using the welcome-screen USB APIs on Android](https://github.com/endlessm/kolibri-installer-android/issues/171).

So, I close this one.
