### ISSUE TITLE
Missing thumbnail of the Channel: SAMHSA

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#738]
The Channel `SAMHSA` is missing the thumbnail on the card. 

Test version: Ladybird 6.31-379

![Screenshot 2023-08-09 19 07 17](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/5cecdf27-8bf6-47a6-8ee2-59d28d58305a)

**Comment by jofilizola** [comment]
I've created the thumbnail and the app custom presentation request issue: https://github.com/endlessm/kolibri-explore-plugin/issues/742

**Comment by vanessa-chang** [comment]
duplicate of #742
