### ISSUE TITLE
Channel override: SAMHSA

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#742]
Channel ID: a8e6591f1afa426d859318a0a29d1237

Styling:
- [ ] Custom thumbnail? https://www.dropbox.com/scl/fo/iwk64bj9nd6r450w0h3ks/h?rlkey=mxai6bg4bvy0nj530n5ri24kx&dl=0
- [ ] Custom icon? https://www.dropbox.com/scl/fo/iwk64bj9nd6r450w0h3ks/h?rlkey=mxai6bg4bvy0nj530n5ri24kx&dl=0

**Comment by erikos** [comment]
Follow up just pushed https://github.com/endlessm/kolibri-explore-plugin/commit/ec4c9dbff7056e1e5cc9df99548da83dcc391171
