### ISSUE TITLE
Move welcome-screen to the core plugin code

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-explore-plugin#748]
With #732, the welcome screen no longer deals with choosing between using external (USB) storage or internal storage. This means there is no need to run it before Kolibri starts. Instead, let's move the welcome screen code to the plugin's core Vue code - this should relate nicely to [DownloadPage.vue](https://github.com/endlessm/kolibri-explore-plugin/blob/master/kolibri_explore_plugin/assets/src/views/DownloadPage.vue) - and remove the welcome-screen package entirely.

This will require some additional changes in the Android and Windows app to support the new behaviour.

**Comment by dbnicholson** [comment]
I bumped the priority because this would make Endless Key Flatpak much simpler. Otherwise we have to repeat what was done with the Android and Windows apps, which is to:

* Run the welcome screen as a standalone web app prior to starting Kolibri.
* Provide a Javascript interface to allow the welcome screen to set the initial content pack.

**Comment by manuq** [comment]
Some progress: https://github.com/endlessm/kolibri-explore-plugin/pull/793

**Comment by manuq** [comment]
Almost there. I still need to adjust the routing so:
- User is redirected to /welcome when there is no content in the database and no download is in progress
- Adapt the wrapper apps (Android, Windows, Flatpak?)

**Comment by dbnicholson** [comment]
> * Adapt the wrapper apps (Android, Windows, Flatpak?)

I'm hoping this is simply "rip out the separate welcome screen code and just start Kolibri". Is something else needed?

**Comment by manuq** [comment]
> > * Adapt the wrapper apps (Android, Windows, Flatpak?)
> 
> I'm hoping this is simply "rip out the separate welcome screen code and just start Kolibri". Is something else needed?

Yes. Only just not rip out, rename it to "loading screen". Here is a PR for Android: https://github.com/endlessm/kolibri-installer-android/pull/183

Untested because my local environment is misbehaving, checking toolbox status.

**Comment by manuq** [comment]
OK I finished the wiring, all is ready for review:
- kolibri-explore-plugin PR: https://github.com/endlessm/kolibri-explore-plugin/pull/793
- kolibri-installer-android PR: https://github.com/endlessm/kolibri-installer-android/pull/183
- endless-key-app PR: https://github.com/endlessm/endless-key-app/pull/156

**Comment by erikos** [comment]
Verification needs #815 - blocked until then.

**Comment by vanessa-chang** [comment]
Verified passed with v0.7 dev test package
