### ISSUE TITLE
Replace Welcome Screen Assets

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#756]
The assets of the welcome screen still have that old typo. These new ones are the same size and aspect ration, but no text: also localization-proof if we don't get to finish the refresh of this page.
![image 99](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/52ef68f2-3fff-4740-9780-923bfb78f124)
![image 100](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/870cefde-5a27-413b-a007-c3156db4064e)

**Comment by jofilizola** [comment]
@jprvita

**Comment by dylanmccall** [comment]
Hi @jofilizola! Just to be sure, is it intentional that these new assets are zoomed out a bit more than the originals? The old ones were cropped differently, like https://github.com/endlessm/kolibri-explore-plugin/blob/2bc544ad2fd733b74230bf2e635bc96320492232/packages/welcome-screen/src/assets/welcome-bg-bottom-left.jpg.

I added a comparison in https://github.com/endlessm/kolibri-explore-plugin/pull/757#issuecomment-1683158456.

**Comment by jofilizola** [comment]
Ha! I think I exported the full assets and Manuel cropped them. Here they are, cropped the same.
![bottom-left-cropped](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/fb5b137b-bef5-4a01-986e-2a3fd8879df6)
![top-right-cropped](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/6ea94d7c-b53f-46d3-9be4-056edaa296d4)

**Comment by jprvita** [comment]
Here how it looks with the new assets:
![Screenshot from 2023-08-18 11-07-35](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/5a1ef750-b2eb-4ff4-81bd-abd766e6b732)

And the original ones, for comparison:
![Screenshot from 2023-08-18 11-15-13](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/0bc0851f-424a-46a1-8872-03bae90045e4)

If you look very closely you can tell the new assets are a tiny bit more "zoomed out" (ex., the new "read aloud" tile has a smaller piece cut-off), but I don't think it matters or have any negative effect, so I'm marking the PR as ready for review + merging again.

**Comment by jofilizola** [comment]
Looks good to me! Thank you, thank you!

**Comment by jprvita** [comment]
Merged!

**Comment by erikos** [comment]
And built https://github.com/endlessm/kolibri-explore-plugin/actions/runs/5904366677

**Comment by vanessa-chang** [comment]
Verified Passed in Chromebook Manatee 6.38-389 & Windows 6.38.5.0
