### ISSUE TITLE
Android app: App must target Android 13 (API level 33) or higher

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#759]
You won't be able to release app updates (13 days away)

![Screenshot from 2023-08-18 13-46-28](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/aae58e71-0dff-4594-8efe-915635539334)

https://play.google.com/console/u/0/developers/6541700215397866681/app/4972213255602582038/policy-center/issues/4989722986023219456/details

Date sent: Aug 11, 2023
**Deadline: Aug 31, 2023**
Violation: App must target Android 13 (API level 33) or higher
Details: To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From Aug 31, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

**How to fix**
Your highest target API level is Android 12 (API level 31).

To ensure that you can continue to make updates to your app you must:

Update your app to target Android 13 (API level 33).
Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.

**Comment by pwithnall** [comment]
I’m looking at this now

**Comment by pwithnall** [comment]
The [API diff from 31 → 32](https://developer.android.com/sdk/api_diff/32/changes) looks like it’s just added API and undeprecated a few APIs, so it shouldn’t require any changes in our code.

The [API diff from 32 → 33](https://developer.android.com/sdk/api_diff/33/changes) is much bigger, but I can’t immediately see anything which should impact on us.

Grepping for the key APIs mentioned in the [API 33 notes](https://developer.android.com/about/versions/13/behavior-changes-all) gives no results.

I’ve bumped the dependency version locally and have built an apk and am trying to run it on an emulator, but it’s failing when loading the main explore page, with the following JS error:
```
08-18 14:57:08.264  7170  7170 E EKWebConsole: TypeError: external_kolibriCoreAppGlobal_urls_default(...).kolibri:kolibri_explore_plugin:get_download_status is not a function -- Source: http://127.0.0.1:55397/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.16.0b1.js
```

To me, this looks unrelated to the Android API version, so either I’ve built the apk incorrectly (with the wrong versions of Kolibri and kolibri-explore-plugin) or I’ve hit a separate bug (or I’m wrong). I’ll dig further.

**Comment by pwithnall** [comment]
Success! I’ve managed to build it for Android 13 and some smoketesting in the emulator says it’s OK:
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/53172/0a265feb-b530-4ac1-8c6f-292238a5de13)

PR available as https://github.com/endlessm/kolibri-installer-android/pull/179

**Comment by dbnicholson** [comment]
Being built and uploaded in https://ci.endlessos.org/job/kolibri-installer-android/222/.

**Comment by dbnicholson** [comment]
The [upload](https://ci.endlessos.org/job/kolibri-installer-android-upload/96/) failed:

```
Upload failed: 
- This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.
```

Hmm, don't know where that's coming from right now.

**Comment by dbnicholson** [comment]
From `~/.local/share/python-for-android/dists/kolibri/build/outputs/logs/manifest-merger-debug-report.txt`:

```
MERGED from [com.google.android.gms:play-services-measurement-sdk-api:21.2.0] /home/dan/.gradle/caches/transforms-3/cabb42372ed06c7897aea4e5f59f3d96/transform
ed/jetified-play-services-measurement-sdk-api-21.2.0/AndroidManifest.xml:25:5-68
        android:name
                ADDED from [com.google.android.gms:play-services-measurement-api:21.2.0] /home/dan/.gradle/caches/transforms-3/c137c969f35504da8d46614874d0ca6
d/transformed/jetified-play-services-measurement-api-21.2.0/AndroidManifest.xml:24:22-65
uses-permission#com.google.android.gms.permission.AD_ID
```

**Comment by dbnicholson** [comment]
Per `./gradlew dependencies`, `play-services-measurement-sdk-api` is a transitive dependency on `firebase-analytics`. Per the [Google Play documentation](https://support.google.com/googleplay/android-developer/answer/6048248), apps targeting Android 13 (API level 33) need to to declare the `com.google.android.gms.permission.AD_ID` permission. That explains why this change triggers the issue.

I suppose a per user unique ID is an expected part of using Firebase Analytics. I'll look into this some more.

**Comment by dbnicholson** [comment]
I tried to [upload again](https://ci.endlessos.org/job/kolibri-installer-android-upload/97/), but I guess it was already there in internal testing. So, I think this is ready to verify on internal testing, but I think we'll need to promote this to production to meet the deadline.

**Comment by dbnicholson** [comment]
@vanessa-chang can you QA the internal testing version Manatee 6.38-389 so we can promote it to production?

**Comment by vanessa-chang** [comment]
@dbnicholson Manatee 6.38-389 has been promoted to production yesterday and it's been tested.

No new issues were found.

**Comment by dbnicholson** [comment]
Oops, that was the wrong version. The upload job was trying to use the version from the last *successful* build. The one we actually want is 6.38-391 from https://ci.endlessos.org/job/kolibri-installer-android/222/.

**Comment by vanessa-chang** [comment]
@dbnicholson oh, thanks. Is there any ways that I can reproduce the original API issue? As I didn't seen the issue while testing the 6.38-389 version though. I will QA the 391 version tomorrow and let you know if it can be promoted to the production. Thanks a lot.

**Comment by vanessa-chang** [comment]
@dbnicholson Hi Dan, thanks. 392 has been tested and it's verified passed with a green light to promote to production.

Thank you!

**Comment by dbnicholson** [comment]
I promoted Manatee 6.38-392 to production and now it's in review.

**Comment by dbnicholson** [comment]
The production release was reviewed and is now live on Google Play. However, the warning in the play console didn't go away because the Closed Testing and Open Testing tracks still had old versions in them. I promoted 392 to each of those tracks, but now they're in review. We might want to delete at least one of those tracks in the future since we're not really using them.

**Comment by dbnicholson** [comment]
The testing releases were reviewed and now the warning is addressed:

> We recently told you that your app does not adhere to Google Play Developer Program policies. This violation has now been addressed.
>
> Thanks for helping to keep users safe on Google Play. Go to the Policy status page to see if you have any other warnings or issues with your app.

All done now.

**Comment by pwithnall** [comment]
Thank you for testing/promoting, Dan!
