### ISSUE TITLE
Add download buttons to online Instance more prominently

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#761]
# Context

from Rodrigo:

"The California Academy of Sciences has agreed to help us promote the app. They will be posting something on their website and their newsletter. While reviewing the information, I noticed the recommend the online version instead of the app which is fine. I'll be asking her to change that however, in some cases, we won't be able to control that and while chatting with Luke about this, we noticed that the buttons to download the app in the online version are at the bottom and not at the top and there's no CTA to promote app download.
Could the inclusion of these logos and a textual guide to encourage visitors to download the app be a big lift? "

# Specs and assets

> [!NOTE] 
> UPDATED SPECS, according to what discussed with @jprvita on Weekly meeting and Slack.

- Add button that triggers the automatic animated scroll to the bottom, where the store badges are.
- [Figma prototype](https://www.figma.com/proto/Mwgjbi2CHUoTMdkE9aGQfP/EK-Manatee?page-id=501%3A5042&type=design&node-id=525-44171&viewport=-20371%2C242%2C0.79&t=1dmDrnT5CKpNEOkv-1&scaling=min-zoom&starting-point-node-id=525%3A44171&show-proto-sidebar=1&mode=design)
- [▶ Online Instance - EK Manatee - 24 August 2023 - Watch Video](https://www.loom.com/share/0701dbd88d8b46c488223a5f158063eb)
- [Figma board](https://www.figma.com/file/Mwgjbi2CHUoTMdkE9aGQfP/EK-Manatee?type=design&node-id=525%3A42050&mode=dev)

![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/58d44717-bd8a-4069-9c10-3984e6b4e992)

> [!NOTE] 
> OLD SPECS
- ~~Add smaller versions of app stores buttons on the top of the page~~
- ~~Add accompanying copy~~
- ~~Add the "source" parameters to the links so we know where people are coming from~~
- ~~Keep the bottom buttons~~
- ~~[Figma board](https://www.figma.com/file/Mwgjbi2CHUoTMdkE9aGQfP/EK-Manatee?type=design&node-id=511%3A29570&mode=design&t=MqKOqLdOgV5xto8Q-1)~~
- ~~Store badges: https://www.dropbox.com/scl/fo/nymgatj4ha6hqf0k9cmco/h?rlkey=fy9phhpkaqnez9pqatv9ujadv&dl=0~~

~~[Image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/8ed8b211-27d1-42e1-854b-ae62a9a0bcd8)~~

~~[Image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/179c9f2d-28e0-4ab1-a927-e2658acbaed9)~~

**Comment by dbnicholson** [comment]
@jprvita do you think you can have a crack at this?

**Comment by jprvita** [comment]
> @jprvita do you think you can have a crack at this?

Sure!

**Comment by jofilizola** [comment]
Specs updated!

**Comment by jprvita** [comment]
I have a working draft (minus the reactive shortening of the label), but I'm struggling a bit with getting the alignment properly. See below.

Before this change:
![Screenshot from 2023-08-29 12-34-44](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/7e8a1ec1-0069-4f1a-9a96-220069525d1a)

With this change:
![Screenshot from 2023-08-29 12-29-18](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/53842581-3fff-46ba-bd88-6d83be809c92)

@jofilizola Let me know if you have any feedback other than the Library button not being centered.

**Comment by jofilizola** [comment]
Looks good! Tiny detail, are you using the large version of the button? It looks a bit "fat" I would try the small to keep it lighter and more balanced (it's already orange!)

**Comment by jprvita** [comment]
I was using the regular version of the button, but I changed it to small and I agree it looks better (and the "Library" button ends up a bit more centralized). Here how it looks, also with the shorter label on narrow screens:
![Screenshot from 2023-08-30 16-30-49](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/57207d49-30c2-4f36-a589-9fbe85503297)
![Screenshot from 2023-08-30 16-48-49](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/974370b5-4bef-4ebd-8cdd-110a937d9cd9)

**Comment by jprvita** [comment]
I believe this is still pending deployment, but I'm not sure how to do that. @dbnicholson Can you give some guidance (or deploy it)?

**Comment by dbnicholson** [comment]
> I believe this is still pending deployment, but I'm not sure how to do that. @dbnicholson Can you give some guidance (or deploy it)?

Run https://ci.endlessos.org/view/infra-dev/job/kolibri-dev-build/ then https://ci.endlessos.org/view/infra-dev/job/kolibri-dev-deploy/ and check https://key.dev.endlessos.org/. If it all works, repeat with https://ci.endlessos.org/view/infra-prod/job/kolibri-prod-build/ and https://ci.endlessos.org/view/infra-prod/job/kolibri-prod-deploy/.

**Comment by jprvita** [comment]
Deployed!
![Screenshot from 2023-09-13 16-01-03](https://github.com/endlessm/kolibri-explore-plugin/assets/73894/9d326fe6-1ae8-46f6-9303-f5f04af2ea3a)

**Comment by vanessa-chang** [comment]
Verified passed in the latest stable online instance.

Notice:
1. If you minimize the app into a small window (ie: https://user-images.githubusercontent.com/73894/264499288-974370b5-4bef-4ebd-8cdd-110a937d9cd9.png), then the About endless Key & privacy policy section is not displayed. It will recover when it's back in a full screen mode

2. @jofilizola Do we consider for the displays on a mobile phone? If so, then first observation will be an issue.

**Comment by jprvita** [comment]
> Verified passed in the latest stable online instance.
> 
> Notice:
> 
> 1. If you minimize the app into a small window (ie: https://user-images.githubusercontent.com/73894/264499288-974370b5-4bef-4ebd-8cdd-110a937d9cd9.png), then the About endless Key & privacy policy section is not displayed. It will recover when it's back in a full screen mode
> 2. @jofilizola Do we consider for the displays on a mobile phone? If so, then first observation will be an issue.

If we think that is a problem, we should open a separate ticket, as I don't believe it is related to the work done here.

**Comment by vanessa-chang** [comment]
Thanks. I have reported ticket #823. I will close this issue.
