### ISSUE TITLE
Initial Spanish translation

### ISSUE THREAD

**Issue by pwithnall** [endlessm/kolibri-explore-plugin#765]
As part of #760, we want an initial translation done for kolibri-explore-plugin.

**Comment by pwithnall** [comment]
Here are the English versions of the strings. They come in three files because of how kolibri-explore-plugin is split up between frontend and backend, and different frontend modules. `django.txt` is actually a [PO file](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) but I had to rename it to get GitHub to accept it.

[django.txt](https://github.com/endlessm/kolibri-explore-plugin/files/12432344/django.txt)
[kolibri_explore_plugin-messages.csv](https://github.com/endlessm/kolibri-explore-plugin/files/12432345/kolibri_explore_plugin-messages.csv)
[welcome-screen-messages.csv](https://github.com/endlessm/kolibri-explore-plugin/files/12432346/welcome-screen-messages.csv)

**Comment by pwithnall** [comment]
@jofilizola, the English versions of the strings for the kolibri-explore-plugin are above for you to take a look at.

**Comment by jofilizola** [comment]
@pwithnall I am organizing the translation file with screenshots, for people translating it might not be very obvious where things sit, since they are not so familiar with all of the UI element. There are a few things that I need help with, all marked in the document:
- Error messages that I can't force to appear, would you be able to get me screenshots? YELLOW
- Strings that are in the UI with no identifiers listed RED
-  Strings that I could not find where the in the UI they live PURPLE (are these `fade.downloadCompletedLabel` related to the individual content download, card UI?)
- Strings that come straight from Kolibri as they are, the quizzes components are marked in gray, can we use the ones from Kolibri?

Here's [the document](https://docs.google.com/document/d/16spohQ1cssR3bkaAL0Qp71AGoK8m2CPV3x8plRIhSY8/edit), if you see something wrong there, please let me know!

Thanks!!

**Comment by pwithnall** [comment]
Left some comments and some screenshots (where I can easily produce them) in the document.

**Comment by pwithnall** [comment]
Here’s an updated version of the message files, including a lot more messages from other parts of the UI which were previously untagged for translation.

This should now be pretty much the full set of strings to translate.

[LC_MESSAGES.zip](https://github.com/endlessm/kolibri-explore-plugin/files/12597820/LC_MESSAGES.zip)

**Comment by jofilizola** [comment]
Thanks Philip! I'm going through the files and I spotted that the `template-ui-messages.csv` is empty when I open and  I don't see the .json file in the .zip folder. I don't know what I'm missing... could you take a look, please?

**Comment by pwithnall** [comment]
Ah yes, it’s meant to be empty. There aren’t actually any translatable messages in the `template-ui` package.

**Comment by jofilizola** [comment]
Ah, ok! Will there be?

**Comment by pwithnall** [comment]
Not unless someone adds more features to template-ui. The lack of messages to translate is because it doesn’t contain any human-readable strings, not because there are missing translation annotations.

**Comment by manuq** [comment]
> Not unless someone adds more features to template-ui. The lack of messages to translate is because it doesn’t contain any human-readable strings, not because there are missing translation annotations.

@pwithnall did you use master branch for the extraction? I see some: `git grep '$trs' packages/template-ui/`

**Comment by pwithnall** [comment]
@jofilizola Here are the missing template-ui messages for translation: 
[template-ui-messages.zip](https://github.com/endlessm/kolibri-explore-plugin/files/12614242/template-ui-messages.zip)

**Comment by pwithnall** [comment]
And here’s the final batch of strings for translation, from the loading screen:
[loading-screen.zip](https://github.com/endlessm/kolibri-explore-plugin/files/12675478/loading-screen.zip)

Included are the English strings, and my initial (dodgy) Latin American Spanish translation. It’ll need reviewing and tweaking.

**Comment by manuq** [comment]
@pwithnall I took the liberty to start importing the strings after I did QA of the documents. I started with the `kolibri_explore_plugin.app-messages.json` as is the only one in current master. Here is a PR: https://github.com/endlessm/kolibri-explore-plugin/pull/832

I wrote a simple script for this (pasted below for now). You can see in the output that there are some missing string IDs. Probably because of moving messages around between the components.

```
import os
import json
import csv

csv_path = 'Spanish_Translations_kolibri_explore_plugin-messages - kolibri_explore_plugin-messages.csv'
json_path = 'kolibri_explore_plugin/locale/es_419/LC_MESSAGES/kolibri_explore_plugin.app-messages.json'

json_data = {}
with open(json_path) as json_file:
    json_data = json.load(json_file)
    
csv_data = []
with open(csv_path, encoding='utf8') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        csv_data.append(row)

csv_data.pop(0)  # first line is header

total_missing = 0
for i, row in enumerate(csv_data):
    _id = csv_data[i][0]
    translation = csv_data[i][3].strip()
    if _id in json_data:
        if translation == '':
            # Ignore missing ones
            continue
        json_data[_id] = translation
    else:
        print(f'Missing ID: {_id}')
        total_missing += 1

with open(json_path, 'w', encoding='utf8') as json_file:
    json.dump(json_data, json_file, ensure_ascii=False, sort_keys=True, indent=2)

print(f'Total Missing: {total_missing}')

```

**Comment by manuq** [comment]
Here is the script above in a PR: https://github.com/endlessm/kolibri-explore-plugin/pull/834

The import would work like this:
- Save the spreadsheet as CSV
- Run the script to update the JSON, eg: `./scripts/import_translation.py ~/Descargas/Spanish_Translations_kolibri_explore_plugin-messages\ -\ kolibri_explore_plugin-messages.csv kolibri_explore_plugin/locale/es_419/LC_MESSAGES/kolibri_explore_plugin.app-messages.json`

**Comment by manuq** [comment]
This is how it looks in my end. Some translations that were correctly imported (like "READ") are not being translated:
![Captura de pantalla de 2023-09-21 12-40-28](https://github.com/endlessm/kolibri-explore-plugin/assets/83944/e748a35b-1024-44a9-bc23-e196ad647534)

**Comment by jofilizola** [comment]
> And here’s the final batch of strings for translation, from the loading screen: [loading-screen.zip](https://github.com/endlessm/kolibri-explore-plugin/files/12675478/loading-screen.zip)
> 
> Included are the English strings, and my initial (dodgy) Latin American Spanish translation. It’ll need reviewing and tweaking.

@manuq @pwithnall  I've prepared a new document for this: https://docs.google.com/spreadsheets/d/1fYO_rili_EVrdMiG3LTZf6AHyqTo2KG_eaIcL7yh__U/edit#gid=644360418 and used the translations we already had in other documents for the same copy.

**Comment by jofilizola** [comment]
> This is how it looks in my end. Some translations that were correctly imported (like "READ") are not being translated: ![Captura de pantalla de 2023-09-21 12-40-28](https://user-images.githubusercontent.com/83944/269673705-e748a35b-1024-44a9-bc23-e196ad647534.png)

https://docs.google.com/spreadsheets/d/1qtkHtDQOMzfK_8_IQnL59WGK-ub2BjIpsccjac7iYf0/edit#gid=1161103477
Line 26, 21, 22, 23 we have the translation to the media type in this document 

The tabs translations are in this one: https://docs.google.com/spreadsheets/d/1J4OyG-KCARsC0hSc0zC0LOguUdpmVw_YJxYG2HA5rBc/edit#gid=1177927074
lines 72, 74

**Comment by pwithnall** [comment]
> > And here’s the final batch of strings for translation, from the loading screen: [loading-screen.zip](https://github.com/endlessm/kolibri-explore-plugin/files/12675478/loading-screen.zip)
> > Included are the English strings, and my initial (dodgy) Latin American Spanish translation. It’ll need reviewing and tweaking.
> 
> @manuq @pwithnall I've prepared a new document for this: https://docs.google.com/spreadsheets/d/1fYO_rili_EVrdMiG3LTZf6AHyqTo2KG_eaIcL7yh__U/edit#gid=644360418 and used the translations we already had in other documents for the same copy.

https://github.com/endlessm/kolibri-explore-plugin/pull/845

**Comment by erikos** [comment]
Spanish localization of the UI is fully working 7.1 onwards.
