### ISSUE TITLE
Add translation calls to welcome-screen

### ISSUE THREAD

**Issue by pwithnall** [endlessm/kolibri-explore-plugin#770]
Currently the welcome-screen package doesn’t support localisation/translation. It hard-codes English strings in at least:
 * `LoadingInitial.vue`
 * `Welcome.vue`
 * `PackSelection.vue`
 * `PackReady.vue`

Those need to be changed to use a `$trs` array.

**Comment by manuq** [comment]
This won't be needed since we are moving the welcome screens to the plugin. However, the de-hardcoding in this PR will be useful.

**Comment by dbnicholson** [comment]
@manuq gave a spin with the translations from #845 and it worked from a browser. Further testing will be done for #765, I believe.
