### ISSUE TITLE
Feature channel row is not shown 

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#780]
Tested with the latest beta version: Manatee 6.40-394 & Windows 6.40.1.0

The feature channel row is not shown unless you switch to the Library tab then switch back to Discovery page.
But the missing channel icons is fixed.

Chromebook log:
[feature_channel.txt](https://github.com/endlessm/kolibri-explore-plugin/files/12462302/feature_channel.txt)

Windows log:
[kolibri.txt](https://github.com/endlessm/kolibri-explore-plugin/files/12462305/kolibri.txt)

_Originally posted by @vanessa-chang in https://github.com/endlessm/kolibri-explore-plugin/issues/642#issuecomment-1697040570_

**Comment by dbnicholson** [comment]
I didn't see this initially, but I do now. I'll see if I can figure it out.

**Comment by dbnicholson** [comment]
This is definitely fallout from #642 due to b9b60d228ab7e11a7f6f7e222b6a0780dcdc5965. What I wanted to do there was use the root node object from `topicsRoot.rootNodes` because `rootNodes` has the channel metadata's inlined thumbnail set as the `thumbnail` property. Without that, you'd have to search through the channels again to find it.

I think the problem may be that that the use of `rootNodes` in `DiscoveryPageContenPacks` is not synchronized with `rootNodes` being populated. What I see in the console is:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at DiscoveryPageContenPacks.vue:48:1
    at Proxy.renderList (vue.runtime.esm.js:2646:1)
    at fn (DiscoveryPageContenPacks.vue:44:1)
    at normalized (vue.runtime.esm.js:2605:1)
    at Proxy.renderSlot (vue.runtime.esm.js:2701:1)
    at fn (EkSlidableGrid.vue:85:1)
    at normalized (vue.runtime.esm.js:2605:1)
    at normalizeSlot (normalize-slot.js:51:1)
    at VueComponent.normalizeSlot (normalize-slot.js:24:1)
    at Proxy.render (carousel-slide.js:70:1)
```

Which is the change in b9b60d228ab7e11a7f6f7e222b6a0780dcdc5965 trying to find the equivalent node in `rootNodes`. So, I think the possible fixes are:

* Block until `rootNodes` is set with `topicsRoot/SET_STATE`.
* Revert b9b60d228ab7e11a7f6f7e222b6a0780dcdc5965 and add in the missing channel data manually.

@manuq do you have any suggestions here? I can't really wrap my head around the model.

**Comment by manuq** [comment]
> Which is the change in [b9b60d2](https://github.com/endlessm/kolibri-explore-plugin/commit/b9b60d228ab7e11a7f6f7e222b6a0780dcdc5965) trying to find the equivalent node in `rootNodes`. So, I think the possible fixes are:
> 
> * Block until `rootNodes` is set with `topicsRoot/SET_STATE`.
> * Revert [b9b60d2](https://github.com/endlessm/kolibri-explore-plugin/commit/b9b60d228ab7e11a7f6f7e222b6a0780dcdc5965) and add in the missing channel data manually.
> 
> @manuq do you have any suggestions here? I can't really wrap my head around the model.

At a glance, the handlers should set loading state to true while loading and to false after. Maybe that changed? Then the view watches the loading state in order to fetch:
` ` `
    watch: {
      loading() {
        if (!this.loading) {
          return this.fetchHighlighted();
        }
      },
    },
```
Chances are that the view gets mounted fast enough and the loading state already changed. For that we added the following in 0c15a9c477660918087b1f13b0ac860d56b8270d:

```
    mounted() {
      if (!this.loading) {
        return this.fetchHighlighted();
      }
    },
```

**Comment by dbnicholson** [comment]
I tested this locally and I'm pretty sure it works. I'm going to make a release so it can be consumed in the Android app.

**Comment by vanessa-chang** [comment]
This issue cannot be verified

Tested Manatee 6.42-395 & Windows 6.42.1.0

The content selection is missing in both apps.
![Screenshot 2023-09-07 1 01 46 PM](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/e4ffaf4c-fcb1-47b6-9c63-bcac60870cf5)

I will reopen this issue first.

**Comment by dbnicholson** [comment]
Argh. That's a separate bug introduced in the explore plugin with the ongoing translations work. It should be fixed by https://github.com/endlessm/kolibri-explore-plugin/pull/775.

**Comment by manuq** [comment]
> Argh. That's a separate bug introduced in the explore plugin with the ongoing translations work. It should be fixed by #775.

Ouch! In the mean time here is a workaround: #792
It should be OK to temporarily workaround it as we are moving the pack selection to the plugin (that is after Kolibri starts)

**Comment by dbnicholson** [comment]
> > Argh. That's a separate bug introduced in the explore plugin with the ongoing translations work. It should be fixed by #775.
> 
> Ouch! In the mean time here is a workaround: #792 It should be OK to temporarily workaround it as we are moving the pack selection to the plugin (that is after Kolibri starts)

Thank you! I'm going to make quickly test and make another release before merging all of @pwithnall's translation PRs.

**Comment by dbnicholson** [comment]
That worked. Tagging [6.43.0](https://github.com/endlessm/kolibri-explore-plugin/actions/runs/6124844947) now.

**Comment by dbnicholson** [comment]
@vanessa-chang can you test this again on Manatee 6.43-396?

**Comment by vanessa-chang** [comment]
Verified Passed in Manatee 6.43-396 and Windows 6.43.1.0

New issue is found #797 in the new apps. I'm not sure if that's also related to the translations work. I'll close this issue first.
