### ISSUE TITLE
Select Spanish content pack based on locale

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-explore-plugin#786]
A user with a Spanish System should skip the download options and be directed straight to the Spanish pack. The Spanish starter pack was added in https://github.com/endlessm/endless-key-content-private/issues/90.

This has some overlap with https://github.com/endlessm/kolibri-explore-plugin/issues/748. Currently the starter pack is set externally as an option, but after that the starter pack will determined by the plugin. I think in the short term the way to handle this is to let the `INITIAL_CONTENT_PACK` option default be empty. When the plugin is loaded, look up the system locale. If it's Spanish, set it to `spanish`. Otherwise, fall back to the existing default of `explorer`.

**Comment by dbnicholson** [comment]
Yeah, that's a reasonable idea and might be easier to integrate after #784. One though about `INITIAL_CONTENT_PACK`, though. For the Endless Laptop case it's likely we're going to have to set the laptop-specific content pack from the image builder. So, it might be nice to keep `INITIAL_CONTENT_PACK` (or some equivalent) but have it default to an empty string or `None`.

**Comment by manuq** [comment]
I can do this on top of https://github.com/endlessm/kolibri-explore-plugin/pull/793

**Comment by manuq** [comment]
Ready for review: https://github.com/endlessm/kolibri-explore-plugin/pull/813

Note that the PR is on top of https://github.com/endlessm/kolibri-explore-plugin/pull/793. Only the last commit is for this issue.

**Comment by manuq** [comment]
Ready for review again: https://github.com/endlessm/kolibri-explore-plugin/pull/813

**Comment by erikos** [comment]
Verification needs #815 - blocked until then.

**Comment by erikos** [comment]
Test results with plugin version 7.1:

This works fine with the Flatpak. When the Spanish locale is set, the UI is in Spanish and the app tries to automatically download the Spanish starter pack. The actual download itself is not working: https://github.com/endlessm/kolibri-explore-plugin/issues/851

On the Chromebook, the Spanish system language is not picked up by the app. The app is coming up in English still.

**Comment by vanessa-chang** [comment]
Verified passed in Narwhal v7.3.0 on the flatpack. 
Windows app is blocked by as it still has the v7.0.0 for the latest release.
Need a further testing for the Chromebook app.

**Comment by erikos** [comment]
Follow up created for the Chromebook experience: #857
