### ISSUE TITLE
Update Python to 3.9

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-explore-plugin#795]
kolibri-explore-plugin builds with [Python 3.7](https://github.com/endlessm/kolibri-explore-plugin/blob/v6.43.0/.github/workflows/main.yml#L34) now.  However, according to [Status of Python Versions](https://devguide.python.org/versions/#supported-versions), Python 3.7 has been EOL since 2023-06-27.

Here lists the Endless Key's Python version on each platform now:
- Windows: [Python 3.9](https://github.com/endlessm/endless-key-app/blob/v6.43.1/.github/workflows/main.yml#L40)
- Android: Python 3.9 (Based on EOS master)
- Flatpak: Python 3.10 ([GNOME 44 runtime](https://github.com/endlessm/endless-key-flatpak/blob/v0.1/build-aux/flatpak/org.endlessos.Key.Devel.json#L4))

So, let's update kolibri-explore-plugin's Python to 3.9.

**Comment by dbnicholson** [comment]
> * Android: Python 3.9 (Based on EOS master)

That's actually just the host python used for the build. The python built and distributed in the app is defined in the python-for-android recipe, which is currently [3.9.9](https://github.com/endlessm/python-for-android/blob/a6b461a2b5ffadbe99800d10b688a33e40226fe5/pythonforandroid/recipes/python3/__init__.py#L59).

**Comment by starnight** [comment]
The new kolibri-explore-plugin builds with Python 3.9 environment successfully.
