### ISSUE TITLE
Broken presentation of some buttons and footer message

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#797]
In the latest beta versions: Manatee 6.43-396 and Windows 6.43.1.0

There are issues with some presenations, such as:
- keyword search button in the channel page
- footer message in some channels
- folder
- search button in the filter section

<img width="419" alt="Screenshot 2023-09-11 174939" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/30b00df5-62ac-4885-bb43-78fdbc1a7830">
<img width="300" alt="Screenshot 2023-09-11 175002" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/851974e3-c8e1-46d0-8860-28d81e1ea282">
<img width="894" alt="Screenshot 2023-09-11 175031" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/cc1e9280-8c6d-447d-98a9-82b373531e7f">
<img width="600" alt="Screenshot 2023-09-11 175102" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/a4fca890-0822-47cf-8c85-62cada46dc80">

**Comment by manuq** [comment]
Yes this is due to the ongoing internationalization effort. The current workaround in template-ui is broken right now.

**Comment by erikos** [comment]
Can also be seen in the Flatpak version.
![Screenshot from 2023-09-12 09-31-00](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/aabd65fd-e985-430d-86ae-370589a55efb)

**Comment by manuq** [comment]
Either of these PRs would fix it:
- https://github.com/endlessm/kolibri-explore-plugin/pull/784
- https://github.com/endlessm/kolibri-explore-plugin/pull/790

I consider my alternative better https://github.com/endlessm/kolibri-explore-plugin/pull/784#discussion_r1318801015 but I still need to check what @pwithnall says about "sets up language and font settings, Intl polyfills, and imports locale data" in https://github.com/endlessm/kolibri-explore-plugin/pull/784#discussion_r1319787992 and answer.

**Comment by dbnicholson** [comment]
This should hopefully be fixed with 6.46.0. Can you please retest?

**Comment by vanessa-chang** [comment]
I tried the Chromebook version: Manatee 6.46-400
- the issue is fixed by updating from an older package
- If I install a new package from the store, it shows a white screen instead of the download progress page after clicking the download the starter pack (and it seems the download not starting as the screen still shows the white screen after I restart the app after 30 mins)

Windows 6.46.1.0
- passes by either updating or newly installing the package

I will close this issue first and open a new ticket for the Chromebook issue.

**Comment by erikos** [comment]
Verified with Vanessa today in our playthrough, works for me as well: https://github.com/endlessm/kolibri-explore-plugin/issues/802

**Comment by erikos** [comment]
Also verified for the Flatpak version in https://github.com/endlessm/endless-key-flatpak/actions/runs/6169269041
