### ISSUE TITLE
Android app crashes in migration process

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#802]
The current Android build on internal testing fails to start in the migration phase. Version: Manatee 664-397

[Short_log_Manatee_644-397.log](https://github.com/endlessm/kolibri-explore-plugin/files/12589788/Short_log_Manatee_644-397.log)

**Comment by dbnicholson** [comment]
I [cherry picked this](https://github.com/endlessm/kolibri-explore-plugin/commit/00dff35ae8924a184e487cdf6a3c99944fc904aa) to the `stable` branch and will be releasing 6.46.0 with it.

**Comment by erikos** [comment]
With 6.46.0 the app does not crash in the migration process anymore. Thanks Dan. The app starts fine and gets me to the Discovery page.
