### ISSUE TITLE
Download page confirm button assumes the landing page is in router history

### ISSUE THREAD

**Issue by dylanmccall** [endlessm/kolibri-explore-plugin#804]
If a user navigates _directly_ to the download page and downloads a set of content, the "Show me" button at the end of the process will appear to do nothing. This causes endlessm/endless-key-flatpak#40.

**Comment by dylanmccall** [comment]
As far as I can tell, this happens because, instead of directly navigating to the root page, we are attempting to navigate backwards in the router's history: https://github.com/endlessm/kolibri-explore-plugin/blame/v6.46.0/kolibri_explore_plugin/assets/src/views/DownloadPage.vue#L143-L145.

**Comment by dbnicholson** [comment]
I merged the PR to master, but I'm going to backport it to stable since I'm not sure when master will be ready to make releases from.

**Comment by dbnicholson** [comment]
[Backported](14aaf51479a3446d4757253ec8d11dd29d6003e2) to stable. I'm waiting for the CI to complete successfully then I'll tag a release.

**Comment by dbnicholson** [comment]
Released in kolibri-explore-plugin 6.47.0. This can be verified in https://github.com/endlessm/endless-key-flatpak/issues/40.

**Comment by vanessa-chang** [comment]
Verified passed as the Show me button works
