### ISSUE TITLE
Download is not in progress and a white screen is displayed instead

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-explore-plugin#806]
I tried the Chromebook version: Manatee 6.46-400
- the issue is fixed by updating from an older package
- If I install a new package from the store, it shows a white screen instead of the download progress page after clicking the download the starter pack (and it seems the download not starting as the screen still shows the white screen after I restart the app after 30 mins)

Windows 6.46.1.0 does not have this issue.

_Originally posted by @vanessa-chang in https://github.com/endlessm/kolibri-explore-plugin/issues/797#issuecomment-1716867259_

**Comment by erikos** [comment]
Reproduced here the same issue. The app was doing the migration fine but after clearing the app storage and starting again, there is a white screen after selecting the interest - download does not start.

[Full_log_Manatee_646-400.log](https://github.com/endlessm/kolibri-explore-plugin/files/12595064/Full_log_Manatee_646-400.log)

**Comment by dbnicholson** [comment]
```
2023-09-13 10:07:12.221  7635-7787  org.endlessos.Key       org.endlessos.Key                    E  kolibri_explore_plugin.collectionviews: Collection manifest
                                                                                                    /data/data/org.endlessos.Key/files/app/collections/explorer-0001.json not found
```

Apparently, I didn't actually test https://github.com/endlessm/kolibri-installer-android/pull/181. Sorry!

**Comment by dbnicholson** [comment]
Argh, build issue. It decided that the collections.zip that was already downloaded was newer than the released collections.zip and didn't do anything. But that fails because the already downloaded version was the full endless-key-collections repo and the paths are different.

I'll wipe the workspace and try again.

**Comment by dbnicholson** [comment]
I tested the last build locally and it worked from a fresh install. Released in Manatee 6.46-401. @vanessa-chang please verify.

**Comment by erikos** [comment]
Smoke tested with 6.46-401: I was able to get to the Discovery page with that build!

**Comment by vanessa-chang** [comment]
Verified Passed with Manatee 6.46-401.
