### ISSUE TITLE
Key on EOS: No interest picker is shown on first launch

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#808]
No interest picker is shown on first launch, a starter pack is downloaded automatically. After the download of the starter pack (here _Explorer pack_) is finished the complete screen is shown - but the _show-me_ button does nothing.

![Screenshot from 2023-09-13 17-21-37](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/f51ace46-7aee-490e-b093-4d6716c057d9)

One can use the home icon to get to the Discovery page or restart the app.

**Comment by dylanmccall** [comment]
This will be resolved once we have completed the following related tasks:

- [ ] https://github.com/endlessm/kolibri-explore-plugin/issues/748
- [ ] https://github.com/endlessm/endless-key-flatpak/issues/40

**Comment by manuq** [comment]
Should by fixed by https://github.com/endlessm/kolibri-explore-plugin/pull/793
