### ISSUE TITLE
Release Narwhal 7 major version

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-explore-plugin#815]
With the changes from #793, all the apps will need to change their build and launch processes or they'll break. I.e., a flag day. So, we want to make a new major version 7 (codename Narwhal) and then stage the app updates to switch away from current version 6 Manatee. @manuq has already prepped the [app changes](https://github.com/endlessm/kolibri-explore-plugin/issues/748#issuecomment-1718224896).

If you want to make Manatee releases, the desired changes need to be cherry picked to the `stable` branch with the release made from there.

I'm a bit worried about what the automatic trigger to build and release the Android and Windows apps will do when the major version release happens. Hopefully they'll just fail in CI, but I think it may be better to have a way not to have the triggers when making a release.

**Comment by erikos** [comment]
Making this one _unbreak now_, as many things are dependent on this including QA.

**Comment by dbnicholson** [comment]
Specifically, the PRs needed are:

* https://github.com/endlessm/kolibri-installer-android/pull/183
* https://github.com/endlessm/endless-key-app/pull/156

For endless-key-flatpak I opened:

* https://github.com/endlessm/endless-key-flatpak/issues/68

It appears that the android build will fail if it automatically builds the major release. The Windows build is currently restricted to `=~6.0`, so it won't try to build the major release. The flatpak is not currently automatically built by and has explicit versions. So, I think we can make the major release first and then land the app upgrades without accidentally releasing a broken app.

**Comment by dbnicholson** [comment]
I opened #821 to support making a 7.0.0rc1 release candidate. That would make it a lot easier to test the apps with a pre-release since the wheel can be downloaded from PyPI.

**Comment by dbnicholson** [comment]
At this very moment it seems like you can run master, so I'm going to attempt to push a `v7.0.0rc1` tag. I kinda suspect the push a tag flow doesn't work, though.

**Comment by dbnicholson** [comment]
As I thought might happen, pushing the `v7.0.0rc1` tag didn't trigger a release because none of the workflows execute on a push to a tag. I manually started the build workflow with the tag in https://github.com/endlessm/kolibri-explore-plugin/actions/runs/6238801921, but I have a small workflow refactor that should make it work the next time a `v*` tag is manually pushed.

**Comment by dbnicholson** [comment]
That also blew up because download-artifact makes extra directories when you [download all artifacts](https://github.com/actions/download-artifact#download-all-artifacts). I pushed [a commit](https://github.com/endlessm/kolibri-explore-plugin/commit/b0764e27833f3a13d9a32d905a9a791ebb7cabfe) to avoid that and now I'm going to try again with rc2...

**Comment by dbnicholson** [comment]
The PyPI upload failed. Hopefully [fixed](https://github.com/endlessm/kolibri-explore-plugin/commit/b73787ff09c21147a3d173cba3a88c6f09a0fdc5) and trying again with rc3.

**Comment by dbnicholson** [comment]
Finally:

https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v7.0.0rc3
https://pypi.org/project/kolibri-explore-plugin/7.0.0rc3/

**Comment by dbnicholson** [comment]
endless-key-app was [building](https://github.com/endlessm/endless-key-app/actions/runs/6240755439) with 6.47.0 but the 7.0.0rc3 apps-bundle.zip. That's probably going to be broken, so I cancelled it. Unfortunately, I forgot to cancel the Android build and it completed. It's likely broken.

I have a PR that disables app build triggering for major and RC releases.

**Comment by dbnicholson** [comment]
@dylanmccall put together https://github.com/endlessm/endless-key-flatpak/pull/72 to use 7.0.0rc3 in the flatpak. That should give us a chance to smoketest things and possibly QA a few of the items here.

In the meantime, I pushed the `v7.0.0rc4` tag, which properly [created](https://github.com/endlessm/kolibri-explore-plugin/actions/runs/6253367527) the [release](https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v7.0.0rc4). Notice that it did not automatically trigger the Windows and Android builds this time.

Unfortunately, I noticed that the backend translations [weren't included](https://github.com/endlessm/kolibri-explore-plugin/pull/835), but that's not a huge deal as it's one string that's rarely shown.

**Comment by dbnicholson** [comment]
My plan today is to smoketest the debug flatpak using an explore plugin rc. If it runs, test that all the explore plugin localization works. Then release 7.0.0 and get all the apps on it.

**Comment by dbnicholson** [comment]
The smoketest went well. The localization was landed, but it doesn't fully work. I spent some time looking at it but ultimately couldn't figure anything out. I'm going to make the release and we'll just have to keep poking at the translations.

The release is running [here](https://github.com/endlessm/kolibri-explore-plugin/actions/runs/6267805287).

**Comment by dbnicholson** [comment]
The release is out:

https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v7.0.0
https://pypi.org/project/kolibri-explore-plugin/7.0.0/

All the apps have PRs to use it:

* https://github.com/endlessm/endless-key-flatpak/pull/81
* https://github.com/endlessm/kolibri-installer-android/pull/183
* https://github.com/endlessm/endless-key-app/pull/156

**Comment by dbnicholson** [comment]
I also opened https://github.com/endlessm/endless-key-flatpak/issues/82 to make the endless-key-flatpak released so that the flathub build can be updated.

**Comment by dbnicholson** [comment]
The flatpak was updated to 7.0.0 and appears to be working, so I think this can be closed.
