### ISSUE TITLE
Spanish starter pack can not be downloaded

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-explore-plugin#851]
With the latest plugin release 7.1 we have the UI translated to Spanish. The initial animation and the Welcome screen is in Spanish. 

When proceeding in the Welcome screen the Spanish starter pack is not downloaded though - the progress stays at zero percentage.

The URL that is tried is http://127.0.0.1:58297/es-es/explore/#/download/spanish/0001

The starter pack is defined in https://github.com/endlessm/endless-key-collections/blob/main/json/spanish-0001.json - other starter packs have the same naming format
https://github.com/endlessm/endless-key-collections/blob/main/json/artist-0001.json

The UI itself is translated fine. This is just about the starter pack not being downloaded correctly.

**Comment by manuq** [comment]
I see the JSON in the latest release, so is not that: https://github.com/endlessm/endless-key-collections/releases/tag/v0.3.1

**Comment by manuq** [comment]
I reproduced it. On the frontend I see this error:
```
TypeError: Cannot read properties of null (reading 'metadata') at DownloadPage.vue:129:1
```
On the backend I see a 500 error when `start-download` is called in `~/.var/app/org.endlessos.Key/data/kolibri/logs/kolibri.txt`:
```
INFO 2023-09-26 10:20:45,937 cherrypy.access 127.0.0.1 - - "POST /explore/api/ek-collections/start-download" 500 0 "http://127.0.0.1:44041/es-419/explore/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
```

Unfortunately the backend logs don't contain the Python traceback that's potentially causing that 500 error. The `debug.txt` file is empty.

**Comment by manuq** [comment]
The fix seems to be as easy as adding "spanish" to the [list here](https://github.com/endlessm/kolibri-explore-plugin/blob/8e3dc61f2712e1ddc9a0e8e02043da443206bc3a/kolibri_explore_plugin/collectionviews.py#L40-L48). It seems we missed the backend change in https://github.com/endlessm/kolibri-explore-plugin/issues/786

**Comment by erikos** [comment]
Tested with 7.3 - download of the starter pack is working fine now.
