### ISSUE TITLE
Create Endless Key Listing in Spanish

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#855]
We have translated assets and copy for the app listing metainfo. We should have the Spanish version in:

- [ ] Google Play
- [ ] Microsoft Store
- [ ] Flathub

Translated screeshots here: https://www.dropbox.com/scl/fo/nxqdtyyvpkatbl0gcgqcq/h?rlkey=l524pdllrbxkkomm89qmw2ujf&dl=0
Translated copy here: https://docs.google.com/spreadsheets/d/1yVTilb6AWsyUGVncyoYSjtbOdPAEZA_BarnnTfUDxfg/edit#gid=1177927074

**Comment by manuq** [comment]
I'm a bit confused. I can't find where is the metainfo file to be translated for flathub. I will close this as invalid and open 3 different tasks

**Comment by vanessa-chang** [comment]
Tested the latest beta installation:

- [ ] Google play store
- [ ] Windows
- [ ] Flathub
I will create separate tickets for above.
