### ISSUE TITLE
Use different feedback link for Spanish

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#858]
The app should link to a different URL for the feedback form when running in Spanish. Bonus points for preparing this to other languages and use the English URL as fallback.

Spanish link: https://endlessos.typeform.com/to/ohjef1FG 

From Joana: Other languages can be supported by the ai translations that Typeform provides (added to the English form), if the user system's is language that has the ai translation support it will appear translated!

![Image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/c2f4a0c2-e368-4a49-a302-147d8ef26bc6)

**Comment by manuq** [comment]
Ready for review. Note: this will need a redirect URL added to the `endlessos.org` domain. Already requested.

**Comment by erikos** [comment]
Can be tested in plugin release 7.4

**Comment by vanessa-chang** [comment]
Verified passed in flatpak version 0.7 plugin v7.5.0
