### ISSUE TITLE
Run content pack selection even if channels exist

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-explore-plugin#863]
Currently the pack selection is skipped if any channels exist under the assumption that only happens once the pack has been selected. That prevents the content from being preseeded as we're trying to do [in the image builder](https://github.com/endlessm/eos-image-builder/issues/117#issuecomment-1738094529) with the result that the Discovery page is empty.

**Comment by manuq** [comment]
So we should persist the pack selection somewhere. Or use the lack of download state as evidence of "pack hasn't been selected". Maybe the latter, otherwise current users will get a pack selection once again.

**Comment by manuq** [comment]
OK, I have found an issue with the previous PR when a download was attempted in a new session even after the download was completed in a previous session. Not good! This new PR should fix it: https://github.com/endlessm/kolibri-explore-plugin/pull/870

This makes the `get_should_resume` API a bit irrelevant. But honestly I don't want to make further changes without a test suit.

**Comment by dbnicholson** [comment]
I merged that and it got released in 7.7.0. If there are any further issues, I think we should open a new issue.

**Comment by dbnicholson** [comment]
I opened #874 about using the database to persist the download state and pack selection in a more reliable way.

**Comment by vanessa-chang** [comment]
So far, no issues were found on the latest Android and Windows package for resuming the content download.

I will close this issue first.
