### ISSUE TITLE
Channel override: Biblioteca Elejandria

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#878]
Channel ID: dosis-vukov

Styling:
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/bye62xtoquq0f67/AADqXBctIM30ghmBqbgP-Cf1a?dl=0

Options:
- [ ] Has carousel section? NO

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/19e363cb-e15f-4a5f-9f79-04b89baa17f2)

**Comment by vanessa-chang** [comment]
It passes in Narwhal v7.11.0 in spanish pack
