### ISSUE TITLE
Channel override: CK-12 Spanish

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#879]
Channel ID: pizaj-kanus

Styling:
- [ ] Custom primary color? Default: `#008545` 
- [ ] Custom secondary color? Default: `#008545` 
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/4nmhk89br85ip7v/AAAQvlj5ON0wftM9YorNXJ6ja?dl=0

Options:
- [ ] Has carousel section? NO
- [ ] Has filters section? Default: yes
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/001993d5-bed2-455b-8774-184e05f5fe1b)

**Comment by vanessa-chang** [comment]
It passes in Narwhal v7.11.0 in spanish pack
