### ISSUE TITLE
Channel override: Ceibal

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#880]
Channel ID: pakoj-nivuf

Styling:
- [ ] Custom primary color? Default: `#00635D` 
- [ ] Custom secondary color? Default: `#00635D` 
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/ux7q3fdtae62vag/AACT51dSZVFPquTByZRzNYLia?dl=0

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/4d0d0693-2858-4673-b4a6-66d95278afa8)

**Comment by vanessa-chang** [comment]
It passes in Narwhal v7.11.0 in spanish pack
