### ISSUE TITLE
Channel override: Ciensación

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#882]
Channel ID: hodug-hajam

Styling:
- [ ] Custom primary color? Default: `#016A7F` 
- [ ] Custom secondary color? Default: `#016A7F` 
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/ba7z954fdd1k83y/AACTF6xKKjkSE6BlibnFmnEKa?dl=0

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/ea275d3f-eebe-4e6f-aab7-caacb3e33700)

**Comment by vanessa-chang** [comment]
It passes in Narwhal v7.11.0 in spanish pack
