### ISSUE TITLE
Channel override: Proyecto Descartes

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#883]
Channel ID: hotor-tumag

Styling:
- [ ] Custom thumbnail? Provide JPEG file for the channel card
- [ ] Custom icon? Provide PNG that will replace the channel icon uploaded at Kolibri Studio
https://www.dropbox.com/sh/z9dlofq8zxg27em/AAAsn-RCu1kww3lqKfFD4Ny0a?dl=0

Options:
- [ ] Has carousel section? NO
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/ecfcda2a-622a-4d4e-9ca3-cf4ff1ccaaf9)

**Comment by vanessa-chang** [comment]
It passes in Narwhal v7.11.0 in spanish pack
