### ISSUE TITLE
Download different extra metadata for Spanish

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-explore-plugin#891]
According to a new requirement: https://docs.google.com/spreadsheets/d/1tTmp_CqjGHezSw_cpDMKjJZUTyTSykkGlzWpStzCs0U/edit#gid=0

There should be extra metadata imported for Spanish. And as I understand, this should be different than the extra metadata for English.

Currently: the metadata of every other manifest (content pack) is imported. The new requirement is to group the manifests by language and don't import English for Spanish or viceversa.

**Comment by vanessa-chang** [comment]
It verified pass in Narwhal v7.11.0 in spanish pack
