### ISSUE TITLE
Wrong version passed to triggered kolibri-installer-android

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-explore-plugin#895]
Back in #885 I changed the triggering of kolibri-installer-android on releases to use a `repository_dispatch` event. Unfortunately, that passes the tag (with the leading `v`) instead of the version. Unfortunately, [that](https://github.com/endlessm/kolibri-installer-android/commit/b40e28c2dec8c6200e44977c53a4a4d41fe35c5b) breaks the build:

```
Execution failed for task ':app:downloadAppsBundle'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ClientProtocolException: Not Found (HTTP status code: 404, URL: https://github.com/endlessm/kolibri-explore-plugin/releases/download/vv7.9.0/apps-bundle.zip)
```

**Comment by erikos** [comment]
Can be tested with the build of [7.10.0 ](https://github.com/endlessm/kolibri-explore-plugin/actions/runs/6618260969)

**Comment by erikos** [comment]
Build 7.10.427 works fine. QA pass.
